### ISSUE TITLE
SELECTION- Select tools on map no results are returned-6.11.36

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#1]
When using the select tools (polygon, rectangle, etc) on the map no results are returned to the user.

**Comment by ehsan67** [comment]
What is the strategy type? @dhenry-KCI

**Comment by dhenry-KCI** [comment]
Tara,
I don't believe this is an issue anymore, but you probably want to double check.

**Comment by rmeitl** [comment]
@dhenry-KCI @TaraF   - this isn't working, I don't think.
