### ISSUE TITLE
Feature Manager (TMDL-Widget) - 6.36.1 - inspection forms missing 

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#100]
The system does not present the proper inspection form for any asset. Some assets indicate that they have an associated inspection record next to inspection (1), however the form is blank. 

![inspection](https://cloud.githubusercontent.com/assets/8092133/4744247/9d4c3cac-5a2e-11e4-9087-adb63fcaf98c.JPG)

Steps to recreate: 
Selection by Form > Select by TMDL Strategies> All TMDL Strategies
Filter by Geography > District 3 > Montgomery  
Ex: 150014UR, 150015UR

**Comment by TaraF** [comment]
Hi Maggie,

Could you take a look at this issue? (Search Stream Restoration in Montgomery County -- 150014UR is good example).  This seems to be happening in our test environment also:  http://vm-egis01/egis/viewer.html

However, it appears the service call for inspections is returning as expected, just not showing in the UI: http://vm-city102/TMDL/api/Inspections/GetStreamInspections?activityId=e278b543%2D2ee1%2D466f%2Db38e%2D4314641dea24&version=eGISW&browsernocache=Wed%20Oct%2029%2009%3A30%3A03%20GMT%2D0400%202014&date=2013%2D09%2D23T00%3A00%3A00&format=xml 

Thanks,
Tara

**Comment by ecomwu** [comment]
Hi Tara,

I took a look at this issue, and I do follow the steps to get the result. The inspection's information displays correctly on my side.

And I've committed all changes I have so far, you can review it to see whether we still have the same issue on this tab. 

Please let me know if you have any questions.
Thanks,
Maggie
![tmdl issue 100](https://cloud.githubusercontent.com/assets/7735468/4826827/ffaa3e36-5f73-11e4-9819-04be29a7757a.PNG)

**Comment by BrittanyHuber** [comment]
Tested and seems to be working.
