### ISSUE TITLE
Feature Manager (TMDL-Widget) - 6.37 - LUC practice tab is empty

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#101]
The system does not provide information in the associated table LUC Practice for tree planting sites. 

![lucpractice](https://cloud.githubusercontent.com/assets/8092133/4744330/4b3f60dc-5a2f-11e4-93e8-cf50216ff775.JPG)

Selection by Form > TMDL Strategies > Planting Trees 
Filter by Geography > District 3 > Montgomery  
LUC Practice tab is empty for all features

**Comment by TaraF** [comment]
This service is currently missing from the build deployed to SHA test:  http://shagbdapp/TMDL/api/Strategies/GetLucPractices?

**Comment by TaraF** [comment]
This is fixed, please wait to test.

**Comment by TaraF** [comment]
Please test on http://shagbdapp/egis/viewer.html

**Comment by BrittanyHuber** [comment]
Tested and it works.
