### ISSUE TITLE
TMDL Strategy Asset Details (TMDL_Widget) - 6.12.15 - Sites without reviewer record retain information from previous site selected

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#104]
If a site without a reviewer record is selected after a site that has a reviewer record, it displays the previous sites review record information in the review tab. 

![image](https://cloud.githubusercontent.com/assets/8092133/5339795/09292af4-7eb3-11e4-91ea-21109bf5bdb6.png)

![image](https://cloud.githubusercontent.com/assets/8092133/5339796/0c4f0154-7eb3-11e4-9424-d5856e1dbac3.png)

Steps to Recreate:
Select By: Site Selections > Tree Site Selection
Filter By: Geography > District 2 > Cecil County
Site 0700128UT > Reviewer record displaying information correctly
Site 0700004AUT > "0 out of 0" Records, but displaying the review record from 0700128UT

**Comment by ecomwu** [comment]
This issue has been fixed. Please review it later.

**Comment by BrittanyHuber** [comment]
Tested on SHA and is fixed
