### ISSUE TITLE
Site Reports (TMDL_Widget) - 6.74 - Site Reports function does not generate a report

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#105]
When selecting a site selection site in the feature manager, the system does not generate a report when clicking the "Site Report" button. 

![image](https://cloud.githubusercontent.com/assets/8092133/5340263/9ffb746e-7eb8-11e4-9b05-1f289a37f72b.png)

Steps to Recreate:
Select by: Site Selections > Tree Site Selection
Filter by: Geography > District 4 > Baltimore
Select any feature in the feature manager
"Site Report" function does not generate a report

**Comment by ehsan67** [comment]
@ecomwu I wasn't sure if you did the reports in client side

**Comment by ecomwu** [comment]
I thought those site reports were not included in phase 1. Attached the screenshot is report list I have for phase 1 for your reference. 
![report](https://cloud.githubusercontent.com/assets/7735468/5377097/0fee8dc6-804c-11e4-9c2a-d149c17ad706.PNG)

**Comment by BrittanyHuber** [comment]
Tested and all are working except;

Tree inspection reports:

![image](https://cloud.githubusercontent.com/assets/8092133/5380251/ac655b22-8064-11e4-83d0-f9e16c5da1ff.png)

Pavement removal:

same error as above 

to recreate: 
tmdl assets > impervious surface elimination
geography > district 7 
060002UI > inspection report

Unable to test retrofits because there are no retrofits with inspection records.

**Comment by ehsan67** [comment]
@ecomwu  Maggie , could you check if the report URL is correctly generated in Flex side?

**Comment by ecomwu** [comment]
This issue has been fixed. I've committed changes, please review it later.

**Comment by BrittanyHuber** [comment]
phase 2
