### ISSUE TITLE
General Information (TMDL_Widget) - 6.12.14 - General information retained from the first site selected

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#107]
When selecting a tree site, the general information tab always displays the information from the first site selected. If selecting another asset type and then selecting a different tree site, the information from the first tree site selected is still retained. 

![image](https://cloud.githubusercontent.com/assets/8092133/5359861/7035b63c-7f8e-11e4-8ac9-b9a3a19ddac5.png)

![image](https://cloud.githubusercontent.com/assets/8092133/5359863/7bd3d4c4-7f8e-11e4-90a8-eb07bd8e55d3.png)

Steps to Recreate:
Select by: TMDL Strategies > All Strategies
Filter by: Geography > District 5
Site 0801215UT-A (or any tree site) selected displays the correct information
selected 0201738UT (or any other tree site) - will display general information from the first selected site 0801215UT-A 

If you select a swale, the general information works correctly. 
If you select another tree site, it will still display the general information from 0801215UT-A

**Comment by ecomwu** [comment]
Fixed. Please review it later.

**Comment by BrittanyHuber** [comment]
reviewed, and it seems to be working

**Comment by BrittanyHuber** [comment]
Tested on SHA and is fixed
