### ISSUE TITLE
Select by Map - (TMDL_Widget) - 6.12.3 - TMDL ID's not returned for swales

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#108]
When selecting by map, the TDML ID and site names for swales are not returned.

![image](https://cloud.githubusercontent.com/assets/8092133/5360029/b51399da-7f8f-11e4-98de-3338b486e0f0.png)

Steps to Recreate:
Selection > Map
Select by TMDL Strategies > Swales
draw a polygon around a county
returned results are missing TMDL ID's and site names

**Comment by TaraF** [comment]
This issue has to do with information being return by services: GetByPolygon.  I will work with Ehsan to resolve.
