### ISSUE TITLE
VIEWING/EDITING- (TMDL WIDGET)- RESULTS tab 6.27/6.27.1

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#11]
![restoration_tab](https://cloud.githubusercontent.com/assets/4129185/3192477/c883208a-ece6-11e3-9438-1ba52174473b.JPG)
When the user is reviewing the results tab where , SELECT BY = TMDL STRATEGIES. Stream Restoration the widget relates each STREAM RESTORATION to many STREAM LIMITS. Then within the Limits subtab is a RESTORATION TYPE field. Each Limit has many RESTORATION TYPE(s) with each unique RESTORATION TYPE being separated by a comma. Currently, the returned results are showing the same RESTORATION TYPE for each LIMIT and not the unique RESTORATION TYPE for each RESTORATION LIMIT.

**Comment by ecomwu** [comment]
I've fixed this issue and committed my change to repository as well. Please test it later.

**Comment by dhenry-KCI** [comment]
Fixed
