### ISSUE TITLE
Asset Reports - (TMDL_Widget) - 6.74 - are not displaying accurate information

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#110]
Asset reports are not pulling the correct information.

Steps to Recreate:
TMDL Strategies > All TMDL Strategies
Filter By > Geography > District 5
Site 080502
Asset Report
AD Date, Bid Date, NTP Date, Proposed Build Start Date - do not match the database

**Comment by ehsan67** [comment]
@BrittanyHuber  can you provide values for those fields that are wrong?

**Comment by BrittanyHuber** [comment]
Ehsan/Dustin, 

I think the report is pulling the correct information, the database just hasnt been updated to reflect new edits. 

![image](https://cloud.githubusercontent.com/assets/8092133/5475607/7bb2864c-85e8-11e4-8ff7-74611427a598.png)

One other thing... @dhenry-KCI did we want null values to populate as "NULL" or "1/1/0001"?

**Comment by dhenry-KCI** [comment]
@ehsan67 we should display null date values as "NULL" not 1/1/001

**Comment by ehsan67** [comment]
@dhenry-KCI that's related to Eric's side

**Comment by BrittanyHuber** [comment]
@dhenry-KCI Information is correct, however the update to display "Null" instead of "1/1/001" has not been happened yet.

**Comment by BrittanyHuber** [comment]
Working on both KCI and SHA
