### ISSUE TITLE
Contract Information - (TMDL_Widget) - contract information is not displaying correctly

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#111]
Contract information is not displaying in the Results tab or in the asset report for Pavement Removal and Stream Restoration Assets. However, the contract information is available through the related table in the HISDEV_NEW database.

The Results tab indicates that there is an associated Contract, but the information is blank. 

![1](https://cloud.githubusercontent.com/assets/8092133/5666800/590f068e-9730-11e4-8747-74cd513dd22f.png)

When an Asset Report is generated, the Contract information is completely blank. 

![2](https://cloud.githubusercontent.com/assets/8092133/5666809/69f30f9a-9730-11e4-8868-8b14a439d4d9.png)

However, in HISDEV_NEW, contract AT4258182 is associated to the site in the related TMDLEDIT.TMDL_CONTRACT table.

![3](https://cloud.githubusercontent.com/assets/8092133/5666812/72b0b1aa-9730-11e4-9392-0ebd2a45407b.png)

Steps to recreate:
Pavement Removal (none of the pavement assets displayed contract information):
Select by form > TMDL Strategies > Impervious surface elimination > Geography > District 7 
Structure ID 130102UI
Structure ID 130103UI
Structure ID 100128UI

Stream Restoration (some streams did show the associated contract but these did not):
Select by form > TMDL Strategies > Stream Restoration > Geography > District 7 
Structure ID: 100006UR
Select by form > TMDL Strategies > Stream Restoration > Geography > District 4
Structure ID: 030010UR

Additional Note - The functionality seems to be working fine for other assets. The following assets were verified and are working properly:
Urban Tree Planting Structure ID: 120053UT
Urban Tree Planting Structure ID: 100008UT
Bioswale SWMFAC # 100332
Wet Ponds & Wetlands   Structure ID: 130001AW
Urban Stream Restoration Structure ID: 030007UR
Urban Stream Restoration Structure ID: 120003UR

**Comment by BrittanyHuber** [comment]
@TaraF - I was unsure who to assign. I am not sure if this is a data related issue or not. If it is, I cant seem to pin point why some streams are displaying correctly while others are not.

**Comment by TaraF** [comment]
In the database,  it appears the contract status is null.  The contract status must be active, or it will not find it.  It is getting a count of 1 you see in the tab because the contract exists.  It gets no information for it however, because the status is null.  Ehsan worked with me to track this down in the database -- the webservices / oracle packages depend on the status field to have a value.

**Comment by BrittanyHuber** [comment]
data issue. will fix in production DB
