### ISSUE TITLE
PROD Test - Stream asset geometry error 

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#114]
When selecting a stream asset, the system returns a queryService fault 400, "Invalid or missing input parameters."

To rectreate:
Strategies > Stream Restoration
District 2 (all streams have the same issue)

**Comment by TaraF** [comment]
Available -- please test in SHA DEV:  http://shagbdapp/egis/viewer.html

**Comment by BrittanyHuber** [comment]
works in DEV ready for PROD

**Comment by BrittanyHuber** [comment]
works in PROD
