### ISSUE TITLE
PROD Test - Stream Inspection Details tab showing incorrect number 

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#115]
When a stream site does not have an inspection, the number on the Inspection Details tab is retained from the previous site selected. 

To recreate:
Strategies > stream restoration
District 4
120006UR > 1 inspection, 1 Inspection detail
120007UR > 0 Inspections, 1 Inspection detail

**Comment by BrittanyHuber** [comment]
@TaraF could you take a look to see if this is working for you?

**Comment by TaraF** [comment]
This issue persists in KCI dev also.  Also noted here, the Insp. Details tab had +, - functions that needed to be disabled for Phase I.

**Comment by TaraF** [comment]
This is fixed, please wait to test until in SHA environment and you are notified.

**Comment by TaraF** [comment]
Available -- please test in SHA DEV:  http://shagbdapp/egis/viewer.html

**Comment by BrittanyHuber** [comment]
works in DEV ready for PROD

**Comment by BrittanyHuber** [comment]
works in PROD
