### ISSUE TITLE
DEV Test - Admin Tab - contracts

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#119]
The dev system allows admin users to add/delete contracts, however I am unable to assocaite consultants to the contract or update any other information other than project number, FMIS, and contract type. 

When the Associate Consultant button is clicked, the system does not respond.

**Comment by BrittanyHuber** [comment]
@TaraF - I was able to close out and retest - I am able to associate consultants now.

**Comment by TaraF** [comment]
As of now, the widget is set up to only allow editing on Project Number, FMIS, and Contract Type.  Please let me know if any additional fields are needed to be edited.

Also, there was an issue where the consultant list was not showing up, either for the Associate Consultant button on  the Contracts tab, nor in the Firm Name drop down list in the Consultants button.  Both have been fixed, and the list is available at the first time use.

Please wait to test until pushed to SHA environment, and you have been notified.

**Comment by TaraF** [comment]
Available -- please test in SHA DEV:  http://shagbdapp/egis/viewer.html

**Comment by BrittanyHuber** [comment]
works in DEV ready for PROD

**Comment by BrittanyHuber** [comment]
works in PROD
