### ISSUE TITLE
SELECTION RESULTS (TMDL WIDGET) - number of records in results tab

### ISSUE THREAD

**Issue by rmeitl** [dhenry-KCI/TMDL-_Tracking-Widget#12]
6.12.3.1
The system will show the number of records returned as the result of any query on the Results Tab.
(Is it possible to put this dynamic piece of text behind Selected TMDL Strategies: 54 results?)

**Comment by ecomwu** [comment]
yes. It can be dynamically changed based on selection result. I will add it.

**Comment by ecomwu** [comment]
I fixed it and committed my change to repository. Please test it later.

**Comment by dhenry-KCI** [comment]
Fixed
