### ISSUE TITLE
DEV Test - Admin Tab - consultants

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#120]
In the admin tab, the user is able to add and delete consultants, however, when adding a point of contact in the create a new consultant dialog box, it does not retain the information.

To recreate:
add a new consultant
Name - test
point of contact - test
Finish
only the name is retained, the point of contact is null. 
You are able to add the point of contact after the new consultant has been created.

Minor enhancement - After you delete the consultant, the name disappears from the drop down menu, but the information (firm name and point of contact) remains until you select a different firm or leave the tab. (when deleting a contract all information clears from all fields)

**Comment by TaraF** [comment]
Fixed: adding a point of contact when adding a consultant is now retained. 

Fixed: after deleting a consultant, the information in the grid below also disappears.

Please wait to test until pushed to SHA environment and you are notified.

**Comment by TaraF** [comment]
Available -- please test in SHA DEV:  http://shagbdapp/egis/viewer.html

**Comment by BrittanyHuber** [comment]
works in DEV ready for PROD

**Comment by BrittanyHuber** [comment]
works in PROD
