### ISSUE TITLE
PROD Test - Streams - General Tab

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#121]
In the general tab for stream assets, there are mulitple fields that appear twice:

structure type
structure name
mast type
stream name
stream report 
stream use
stream order
site name
land use
closest crossing
stream length
linear feet restored
notes
gen com

To Recreate: 
assets > stream restoration  > District 3 > 150001UR

Also, the field STRUCTURE NAME in the General tab is Null in the widget, but populated in the database.  (this is for all streams)

**Comment by TaraF** [comment]
Both items above have been fixed. Please wait until in SHA environment and you have been notified.

**Comment by TaraF** [comment]
Available -- please test in SHA DEV:  http://shagbdapp/egis/viewer.html

**Comment by BrittanyHuber** [comment]
works in DEV ready for PROD

**Comment by BrittanyHuber** [comment]
works in PROD
