### ISSUE TITLE
Advanced Query Builder - Field Name

### ISSUE THREAD

**Issue by Jdeluca16** [dhenry-KCI/TMDL-_Tracking-Widget#124]
Field Names in Advanced Query Builder begin with "f."   this should be removed.   E.G. f.MAST_TYPE
![f in name](https://cloud.githubusercontent.com/assets/10602639/6417849/426b5a66-be7e-11e4-9bd4-31caf400a864.PNG)

**Comment by Jdeluca16** [comment]
This is on KCI Dev

**Comment by BrittanyHuber** [comment]
corrected.
