### ISSUE TITLE
Advance Query Builder - No Results Returned

### ISSUE THREAD

**Issue by Jdeluca16** [dhenry-KCI/TMDL-_Tracking-Widget#127]
I am not getting results returned from the advanced query builder for my queries.   is this because of limited test data in the database or a problem with the query.  an examply of a query i am running is attached.
![no results](https://cloud.githubusercontent.com/assets/10602639/6418516/a5b5e2bc-be83-11e4-94b8-0dfe2ec07ed6.PNG)

**Comment by BrittanyHuber** [comment]
corrected
