### ISSUE TITLE
Edits not shown in the Feature Manager

### ISSUE THREAD

**Issue by Jdeluca16** [dhenry-KCI/TMDL-_Tracking-Widget#130]
After making edits to an attribute the results are not shown in the feature manager table.   They are supposed to appear in Red.    To recreate the issue, search on TMDL stratregies - stream restoration, district 4.   click the select button.   in results select the top record tmdl = 030005ur.   add the number 2 to the end of teh site name.   no change appears to the data at the top in the feature manager table.  Changes only appear in the bottom section where the edit was made. 
![name change](https://cloud.githubusercontent.com/assets/10602639/6420276/c26e35e4-be92-11e4-889f-459404afffe3.PNG)

**Comment by Jdeluca16** [comment]
This is on KCI Dev

**Comment by BrittanyHuber** [comment]
After making edits to the Site Name in the attribute manager, the edits do not appear in the feature manager until the selection is made a second time. 

Steps to recreate:
TMDL Strategies > Stream Restoration
District 4 > Baltimore
030004UR
Site Name = I 83 Piney Creek 
Edit to = Piney Creek 
Save Edits 
The feature manager still displays "I 83 Piney Creek"
![image](https://cloud.githubusercontent.com/assets/8092133/6463994/20ab264a-c185-11e4-8a5e-5af57e0c8476.png)

Upon recreating the selection:
TMDL Strategies > Stream Restoration
District 4 > Baltimore
The edited Site Name "Piney Creek" now appears in the feature manager 
![image](https://cloud.githubusercontent.com/assets/8092133/6464044/86873fb2-c185-11e4-9c5e-cd11e09a90e8.png)

Should this repopulate on the save, or is there another system refresh that needs to occur in order for the edits to appear in the feature manager?

**Comment by GraceAi** [comment]
Fixed. Feature manager will be repopulated on the edit and save. It will get restored if the edit is not saved.

**Comment by BrittanyHuber** [comment]
Verified that this works in KCI DEV
