### ISSUE TITLE
Issue Creating/Updating Inspections

### ISSUE THREAD

**Issue by Jdeluca16** [dhenry-KCI/TMDL-_Tracking-Widget#132]
In the KCI Dev environment, while view results from a search on stream restorations in district 3, i selected stream restoration TMDL 160014ur.   when i click on inspections, the add inspection button is grayed out.   This is in reference to requirement 6.36.7.   see attachment for details.
![gray add inspection button](https://cloud.githubusercontent.com/assets/10602639/6420906/4ce5e7c6-be98-11e4-8bf6-ce9d884a7465.PNG)

**Comment by BrittanyHuber** [comment]
Verified that this is working in KCI DEV. Inspection records are not added with the “Add” button on the editor toolbar, they are added with the (+) button in the inspection tab.
