### ISSUE TITLE
Advance Query Wildcard (Like) Returns No Results

### ISSUE THREAD

**Issue by Jdeluca16** [dhenry-KCI/TMDL-_Tracking-Widget#133]
In the KCI dev environment, when running a selection query in the Advanced Query Builder, using the wildcard operator of "Like" returns no results.  
To duplicate the issue, select advance query builder enter the following information
field name = orig_milestone_year
operator = Like
input value = 201

**Comment by Jdeluca16** [comment]
this may deal less with with the wildcard search and more with the overall database connection/search results in the Advanced Query Builder

**Comment by BrittanyHuber** [comment]
Needs to include the % in the input value. verified that this is working in KCI DEV.
