### ISSUE TITLE
Issue with the Advance query builder connecting to the database

### ISSUE THREAD

**Issue by Jdeluca16** [dhenry-KCI/TMDL-_Tracking-Widget#135]
while working in the KCI Dev environment, in advanced query builder, there is an issue pulling data from the database.    Select TMDL Strategies, all TMDL Strategies field name = ac.status, operator = "=".   this should populate the values in the Unique Value field, however no values are returned.   the unique value field can not be populated.

see screenshot for additional details.
![status](https://cloud.githubusercontent.com/assets/10602639/6443731/f0568ce6-c0c6-11e4-8319-4c2a8bf9c2bb.PNG)

**Comment by dhenry-KCI** [comment]
Corrected
