### ISSUE TITLE
System Wont Cancel Spatial Edits 

### ISSUE THREAD

**Issue by Jdeluca16** [dhenry-KCI/TMDL-_Tracking-Widget#136]
Working in the KCI Dev environment, after making a spatial edit, if the user clicks cancel the change does not get undone.   to recreate do the following steps:
Select by filter TMDL Strategies and all TMDL Strategies
filter by geography and select district 4
in the results select TMDL 030197UT
check the enable editing and click edit shape
move a vertice 
in the edit TMDL shape box select cancel 
in the next box click yes.  
the box dissapears but the spatial edit remains. 
![edit](https://cloud.githubusercontent.com/assets/10602639/6443922/69f61b9c-c0c8-11e4-984b-e2c4881e36fe.PNG)

**Comment by GraceAi** [comment]
This is fixed.

**Comment by dhenry-KCI** [comment]
Corrected
