### ISSUE TITLE
The system should limit input to the type of field

### ISSUE THREAD

**Issue by Jdeluca16** [dhenry-KCI/TMDL-_Tracking-Widget#137]
working in the KCI dev environment with TMDL 030197UT Site name BA00257 in results under the activity tab the system allows users to enter and save any characters for the Original Mileston years.  This should be limited to numeric values.  
![name change](https://cloud.githubusercontent.com/assets/10602639/6448022/01187b3e-c0e5-11e4-9111-1374cf3e88f5.PNG)

**Comment by GraceAi** [comment]
Fixed. Added validation logic on save.

**Comment by dhenry-KCI** [comment]
Corrected
