### ISSUE TITLE
Pavement Removal Site Selection should display area in Sq yards not in feet 

### ISSUE THREAD

**Issue by Jdeluca16** [dhenry-KCI/TMDL-_Tracking-Widget#138]
working in the KCI dev environment, results for Pavement Removal Site Selection  should display area in square yards per requirement 6.15.  It is currently displayed in FT (see screenshot below).  To reproduce this select in the filters Site selection - Pavement Removal Site Selection.   filter by geography and district 4.  In the results scroll select S SID 0300003UI.  scroll down the attributes.  
![area in feet](https://cloud.githubusercontent.com/assets/10602639/6445274/d9e49638-c0d0-11e4-9471-41d49ca8c41d.PNG)

**Comment by BrittanyHuber** [comment]
Requirement 6.25 lists incorrect fields for pavement removal site selection. The fields listed in the widget match those in the DB. This is not a bug.
