### ISSUE TITLE
SELECTION (TMDL WIDGET)- Select by Form -Select Button

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#14]
If a user has entered their filter criteria, (Strategy and Strategy Type and then Contract or Geography) and they hit the select button to display the results if there are no results to display the widget should alert the user with "The Selection has found no results. Please try a new selection."

**Comment by TaraF** [comment]
This enhancement is in place. Please review with next release.

**Comment by dhenry-KCI** [comment]
This enhancement is in place when the user clicks "Validate" but it does not work when the user clicks "Select". Please alert the user when they click "Select" if no records are available.

**Comment by dhenry-KCI** [comment]
This has been fixed.
