### ISSUE TITLE
Editing Geometry Successful Message When Nothing Was Edited

### ISSUE THREAD

**Issue by Jdeluca16** [dhenry-KCI/TMDL-_Tracking-Widget#140]
In the KCI dev Environment,  after enabling edit, clicking the move button, and clicking finished in the popup window, a message appears stating that " The geometry for TMDL # has been moved successfully"   this error is confusing because no edit was made.  also, since nothing was selected, no # is provided.   This message should be changed to state something like "no changes made"
![edit message](https://cloud.githubusercontent.com/assets/10602639/6447843/cf7b6614-c0e3-11e4-8f7a-9903f07afa7a.PNG)

to recreate, select any feature in the results tab and check the Enable Editing button.   click move then click finished.

**Comment by GraceAi** [comment]
This is fixed.

**Comment by BrittanyHuber** [comment]
Verified that it is working in KCI DEV
