### ISSUE TITLE
System Locks up when Associating New Contract

### ISSUE THREAD

**Issue by Jdeluca16** [dhenry-KCI/TMDL-_Tracking-Widget#142]
working in the KCI dev environment, when associating a new contract to an existing record, if no contract is selected the system will lock up.    to recreate this issue take the following steps
1. select by TMDL Strategies -  Planting Trees or Forestation on Pervious Urban
2. filter by geography and select district 4 in the dropdown.  then click on select
3. click on TMDL 030205UT and the Contracts tab
4.  click Assoc NEw Contract
5. without selecting a contract click add contract

**Comment by GraceAi** [comment]
Fixed by adding validation. Contract can't be null

**Comment by dhenry-KCI** [comment]
Corrected
