### ISSUE TITLE
Error Message When Adding LUC Practice

### ISSUE THREAD

**Issue by Jdeluca16** [dhenry-KCI/TMDL-_Tracking-Widget#144]
Working in the KCI Dev Environment, when adding a new Luc Practice to a record if a letter is entered instead of a number to the Total Trees field and error message pops up that states the Asset Editor has encountered a web service error ioError #2032.

to recreate this issue
1.  in the selection tab select by TMDL strategies - planting Trees or Forestation on Pervious Urban
2.  filter by geography and district 4
3.  in the results click on TMDL 030205UT
4.  click on the LUC Practice tab
5.  click the add button
6.  in the post land use dropdown select bare ground
7.  in the total trees field type z and click add Luc Practice
8.  click save
![error message luc](https://cloud.githubusercontent.com/assets/10602639/6449743/f2791fbe-c0f0-11e4-9bbf-148fa7b30c6d.PNG)

**Comment by GraceAi** [comment]
Fixed. Added validation logic when creating and saving a Luc Practice

**Comment by dhenry-KCI** [comment]
Corrected
