### ISSUE TITLE
Typo - Should Say Golden Ring

### ISSUE THREAD

**Issue by Jdeluca16** [dhenry-KCI/TMDL-_Tracking-Widget#145]
working in the KCI Dev environment, under the selection filter by district 4 and Baltimore.   the shop dropdown should be "Golden Ring" not "Goldern Ring"
![golden ring](https://cloud.githubusercontent.com/assets/10602639/6450000/d9c1eabc-c0f2-11e4-9367-cf395154febe.PNG)

**Comment by BrittanyHuber** [comment]
known issue - will correct in DB
