### ISSUE TITLE
PHASE II - KCI DEV - Versioning - 6.9.3 - does not prompt editor/admin user with version options upon enabling editing session

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#147]
Upon initiating an edit session by clicking the enable editing checkbox, the system does not prompt the user with a security role of either EDITOR or ADMIN with the following options:
     - Select between active edit versions available for specific user or, 
     - Create a new child version to the eGIS TMDL widget version for editing

**Comment by TaraF** [comment]
Changes made to satisfy this requirement:

User is now prompted to select / start and edit session if they try to click "Enable Editing"  when not in a current edit session.  

Also, upon trying to change the DB version selected (in upper right of main UI), when there is an active edit session open, the user will be prompted to stop the edit session and either save/cancel edits before switching the db / version. 

Also -- changes were made to honor user roles.  They are as follows:

Admin : full rights, including Versioning Tab and Admin Tab
QC Reviewer: Editing and QC Reviewer rights inside of Versioning tab (no admin tab)
Editor: Editing rights only inside of versioning tab (no admin tab)
Viewer: main viewing capabilities only, no admin or versioning tabs available

This should be fully tested -- either let me know who/when users roles should change, or I can possibly give another person rights to add/remove from the roles list.

Please wait until notified to test these edits.

**Comment by TaraF** [comment]
ready

**Comment by BrittanyHuber** [comment]
@TaraF I am unable to recreate any of these. I am still encountering the same issues....

When an edit session is ended, then enable editing check box is still checked off as if the user is still in an edit session.

I am able to enable editing from the results tab without being prompted to select / start an edit session when I am not in a current editing session. 

I am able to change versions when in an active editing session without being prompted to end the current editing session. 

Also, should I be set up to change my role to test the capabilities of each role?

**Comment by BrittanyHuber** [comment]
verified that it is working in KCI DEV
