### ISSUE TITLE
PHASE II - KCI DEV - Versioning - 6.9 - Selection tab highlighted while working in the Versioning tab

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#148]
While working in the versioning tab occasionally the selection tab will be highlighted as if you were in the selection tab, while all of the information remains consistent with the versioning tab. 

![image](https://cloud.githubusercontent.com/assets/8092133/6527129/46acc6c4-c3e6-11e4-905c-2e59fc23f277.png)

To recreate: 
Create a version > then switch version in the top toolbar back to eGISW version. 
The system highlights the selection tab. 
The user is unable to access the selection tab from here unless you click on a different tab (ie. the results tab) then click the selection tab. The user can then access the selection tab.

**Comment by TaraF** [comment]
This has been resolved (with making user stop edit sessions before switching).  

Please wait to test until notified.

**Comment by TaraF** [comment]
ready

**Comment by BrittanyHuber** [comment]
Verified that it is working in KCI DEV
