### ISSUE TITLE
Site Selection-(TMDL WIdget)- Type Field -6.13

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#15]
The TYPE Field for SIte Selection records is populated in the Feature Manager table but when viewing individual records the TYPE field is NOT populated.
![type field](https://cloud.githubusercontent.com/assets/4129185/3217294/05819bc0-efde-11e3-9479-cd85f4763629.JPG)

**Comment by ecomwu** [comment]
I've fixed this issue and committed my change to repository as well. Please test it later.

**Comment by dhenry-KCI** [comment]
Fixed
