### ISSUE TITLE
PHASE II - KCI DEV - Versioning - 6.9.4 - doesn't default to active version upon login

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#150]
The system does not default to the active version upon log in to the widget. 

To recreate:
Created a version > start editing
Closed out of widget & opened again
Defaults to eGISW version

**Comment by TaraF** [comment]
This is resolved to get the latest edit session by date/time.

Please wait to test until notified.

**Comment by TaraF** [comment]
ready

**Comment by BrittanyHuber** [comment]
Verified that it is working in KCI DEV
