### ISSUE TITLE
PHASE II - KCI DEV - Versioning - 6.9.6 - doesn't disable change version toggle within active edit session

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#151]
The system does not disable to change version toggle if the user is within an active editing session. When switching between versions, the version toggle does not display the name of the version that is currently being edited.

![image](https://cloud.githubusercontent.com/assets/8092133/6527609/07d64e12-c3ea-11e4-86e4-456fe12ce51c.png)

To Recreate:
create a version > start editing
TMDL Strategies > planting trees > District 4 
from the version toggle in the upper right >  switch to a different version

Switch to eGIS
select save
the version toggle says "Editing:   " (does not display which version is currently being edited)

**Comment by TaraF** [comment]
This is resolved (forces user to stop edit session before switching).

Please wait to test until notified.

**Comment by TaraF** [comment]
ready

**Comment by BrittanyHuber** [comment]
Verified that it is working in KCI DEV
