### ISSUE TITLE
PHASE II - KCI DEV - Versioning - 6.9.7 - able to create a new version while in an active editing session

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#152]
The system allows the user to create a new version while in an active editing session. The check mark is removed from the version currently being edited, however the stop editing button is still active. 

![image](https://cloud.githubusercontent.com/assets/8092133/6527660/7f2434e8-c3ea-11e4-8314-5f2d0a309921.png)

![image](https://cloud.githubusercontent.com/assets/8092133/6527638/46373c66-c3ea-11e4-9bab-85b3792960c5.png)

To Recreate:
Create a version 
Start editing
create new version

When the version is added, and each version is selected, they all appear with "stop editing." The user may lose track of which version they were editing.

**Comment by TaraF** [comment]
This has been resolved -- a user must now stop editing before they can create, delete or submit for QC. 

Please wait to test until notified.

**Comment by TaraF** [comment]
ready

**Comment by BrittanyHuber** [comment]
Verified that it is working in KCI DEV
