### ISSUE TITLE
PHASE II - KCI DEV - Versioning - 6.9.8 - does not alert user of active editing session upon closing

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#153]
The system does not alert the user that they are within an active editing session when closing during an active edit session. Upon reopening the widget, the system defaults to the eGISW version and the editing session has been stopped. 

To Recreate:
Create version
start editing
close widget
reopen
eGIS version is now active and the editing session has been stopped on version that was in an active editing session upon closing the widget

**Comment by TaraF** [comment]
The system cannot stop the user from closing the browser tab while in the middle of an edit session, however this was resolved by:

Upon re-entering the widget, if an active edit session was started ("ACS") and not stopped, the user will be forced to stop the session and either save or cancel their edits.  The user will then be set to the latest edit session created, just like normal.  

Please wait to test until notified.

**Comment by TaraF** [comment]
ready

**Comment by BrittanyHuber** [comment]
Verified that it is working in KCI DEV
