### ISSUE TITLE
PHASE II - KCI DEV - Versioning - 6.9.9 - doesn't prompt user to alert QC role that version is ready for QC

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#154]
The system does not prompt the user to alert the QC role that a version is ready to be QC’ed. When submitting a version for QC, the user is able to select a QC'er and sucecessfully submit the version for QC. However, there is not prompt to alert the QC role that the version is ready, it just appears in the QC Reviewer tab. 

![image](https://cloud.githubusercontent.com/assets/8092133/6527864/300962aa-c3ec-11e4-854c-f2c010281d0d.png)

To recreate:
Select version 
Select submit for QC 
Select QC role (Brittany.huber)
Submit successful dialog box appears 

No alert to Brittany.huber that version is ready for QC.

**Comment by TaraF** [comment]
Per our discussion with Dustin (see email) -- the purpose of this requirement was to allow a user to submit to QC upon stopping an edit session.

The resolution provides the user with the choice to submit to QC immediately following the stopping of an edit session, but does not force the user to do so.

Please wait to test until notified.

**Comment by TaraF** [comment]
ready

**Comment by BrittanyHuber** [comment]
Verified that it is working in KCI DEV
