### ISSUE TITLE
PHASE II - KCI DEV - Versioning - 6.9 - stop editing button not activated upon enabling editing from results tab

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#155]
When enabling an edit session in the results tab by selecting the "enable editing" check box, the system does not activate the “stop editing” button in the versioning tab – still says “start editing”

To recreate:
In eGIS version 
select TMDL Strategies > planting trees > district 4
select the enable editing check box in the results tab
In the versioning tab, the version previously created still dispays the "start editing" button
In the results tab, use the version toggle to switch to a different version > save
In the versioning tab the version selected for editing still displays "start editing"
The user is not able to select "stop editing" from the versioning tab

**Comment by BrittanyHuber** [comment]
This becomes confusing. When enable editing is selected in the results tab, the versioning tab does not indicate in any way that a version is currently being edited. A site was deleted from a version I created, and there was no way to undo this action. By unselecting enable editing, without hitting "save"- this saves the delete without prompting the user if they would like to save edits.

**Comment by TaraF** [comment]
This has been resolved. The work flow has been updated to force the user to go to the versioning tab and start and edit session before they can enable the edit functions in the result screen.  If they try, they will be prompted to start and edit session first.  This should prevent unwanted edits without the user being aware that they are in an edit session.

**Comment by TaraF** [comment]
ready

**Comment by BrittanyHuber** [comment]
Verified that it is working in KCI DEV

**Comment by BrittanyHuber** [comment]
@TaraF - upon ending an edit session from the versioning tab - the enable editing check box remains activated in the results tab. The user is able to delete features even though the editing session has been ended.

**Comment by TaraF** [comment]
Fixed: system now auto-removes editing capabilities upon stopping an edit session.  (Also, sometimes a error occurred after stopping an edit session, and making a selection -- this is also resolved).

please wait to test until notified.

**Comment by BrittanyHuber** [comment]
verified that this is working in KCI DEV
