### ISSUE TITLE
PHASE II - KCI DEV - Versioning - 6.9.13.1 - no alert that no results are returned

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#156]
The system does not alert the user that the search criteria returns no results when switching between versions

To recreate:
Create a new version
Search: TMDL Strategies > Wet Pond or Retention Pond > District 4 
Returns no results
Switch to eGIS version using the toggle in the upper right 
Switches to the Selection tab does not warn the user that there are no results

The system should alert the user that no records match the search criteria if toggling between versions creates no results.

**Comment by TaraF** [comment]
This is resolved. The updated workflow will clear all results when switching between database or versions, and will take the user to the selection tab.  The user will need to make a new selection to get results for the new version selected. 

Also, a note has been added to the database / version popup window, notifying the user:
*Note: When switching the database or versions, the results will be cleared and a new selection will need to be made.

**Comment by TaraF** [comment]
ready

**Comment by BrittanyHuber** [comment]
Verified that it is working in KCI DEV
