### ISSUE TITLE
PHASE II - KCI DEV - Advanced Query - 6.11.8 - Acceptance Letter should be unique value

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#158]
When selecting field name "Acceptance Letter" the Unique value field should be activated and provide the list of domain values from the database. 

![image](https://cloud.githubusercontent.com/assets/8092133/6528283/edaf7e78-c3ee-11e4-8c0a-13acef8a52a6.png)

To recreate:
TMDL Strategies > planting trees
Field Name: Acceptance Letter
Operator: = 
Unique Value field disabled (should provide a list from the DB)

![image](https://cloud.githubusercontent.com/assets/8092133/6528314/1bc0874e-c3ef-11e4-96b3-3656923687d7.png)

**Comment by TaraF** [comment]
Hi Ehsan,

Can you take a look at the service for this?  I am not sure that we have a domain class set up for D_Accept_Letter.  Here is the service:  http://vm-city102/TMDL/api/Strategies/GetFieldsInfo?strategyType=FPU&format=xml&browsernocache=Wed%20Mar%2011%2015%3A06%3A18%20GMT-0400%202015 

Here is the return for f.ACCEPTANCE_LETTER:
<TMDLPropertyInfo><DomainName i:nil="true"/><FieldName>f.ACCEPTANCE_LETTER</FieldName><FriendlyFieldName i:nil="true"/><TypeName>String</TypeName></TMDLPropertyInfo>

Thanks!

**Comment by TaraF** [comment]
Sorry, it didn't like the carrots. Here is the return again:

TMDLPropertyInfo
DomainName i:nil="true"
FieldName f.ACCEPTANCE_LETTER
FriendlyFieldName i:nil="true"
TypeNameString
TMDLPropertyInfo

**Comment by ehsan67** [comment]
fixed

**Comment by TaraF** [comment]
f.ACCEPTANCE_LETTER is now available for land use.

**Comment by BrittanyHuber** [comment]
Verified that it is working in KCI DEV
