### ISSUE TITLE
PHASE II - KCI DEV - Create/Add - 6.23.1 - Ag. Review records are not saved

### ISSUE THREAD

**Issue by leeensminger** [dhenry-KCI/TMDL-_Tracking-Widget#159]
While adding an "Ag. Review" record, the system adds the records and related behavior appears correct (i.e., the count on the vertical tab increases, and "Review x of x" is updated).  Upon clicking the Save button, the records appear to be removed and not saved.

Steps to recreate:
1. Within the Ag. Reviews tab of a selected Site Selection feature, and with Enable Editing checked, click Add to add a Review.
2. Enter information and click Add Review.  Note the system behaves correctly as if a record is added.
3. Click Save.
4. The record disappears.

**Comment by GraceAi** [comment]
Fixed by adding validation when creating a new agent review record. Validation includes "REVIEW_GROUP" should not be empty and should not be Consultant. Need to update and republish web service and flex code.

**Comment by dhenry-KCI** [comment]
Corrected
