### ISSUE TITLE
Stream Site Selection (TMDL Widget)- Decode Domain

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#16]
Decode the COST field/domain on Stream Site Selection.

**Comment by ecomwu** [comment]
In requirement document section 6.13, the  field <COST> is marked as editable text input, not a domain. I will ask Ehsan to clarify it.

**Comment by ecomwu** [comment]
I've fixed this issue and committed my change to repository as well. Please test it later.

**Comment by dhenry-KCI** [comment]
Fixed
