### ISSUE TITLE
PHASE II - KCI DEV - Delete/Deactivate - 6.12.15 - Users can only view the first of multiple Ag Reviews

### ISSUE THREAD

**Issue by leeensminger** [dhenry-KCI/TMDL-_Tracking-Widget#161]
When multiple Ag Reviews exist for a site selection feature, the system displays the first review (i.e., "Review 1 of 4").  Upon the user clicking the right arrow to view the next Review, no action is triggered within the system.  The user cannot view the other reviews.

Steps to recreate:
1. Identify a site selection with multiple Ag Reviews (ex: Tree Site Selection, Frederick County, SSID 1000008UT)
2. Click the Ag Reviews tab (4 exist for this feature)
3.  Click the right arrow to view the second of 4 reviews.  The system produces no action.

**Comment by GraceAi** [comment]
Fixed the bug in flex code. Need to update and republish

**Comment by dhenry-KCI** [comment]
Corrected.
