### ISSUE TITLE
PHASE II - KCI DEV - Plat Information Tracking - 6.43.4 - Plat does not delete

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#163]
When a plat record is deleted and edits are saved, the plat is not deleted. 

To Recreate:
Create a version > start editing
Planting Trees > District 4 > 030004UT
Within the results tab enable editing in the editing tool bar
Create a plat record
Save edits
Delete plat record
Save edits 
Plat record reappears
Unselect enable editing from the editing toolbar > delete plat > the plat deletes

Upon clearing the search and selecting Planting Trees > District 4 > 030004UT, the plat still exists.

**Comment by GraceAi** [comment]
Fixed the bug in flex code. Need to update and republish the changes

**Comment by BrittanyHuber** [comment]
Verified that it is working in KCI DEV
