### ISSUE TITLE
PHASE II - KCI DEV - As Built Tracking - 6.58.3 - error when creating an asbuilt record

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#165]
When an asbuilt record is created and added to a site, the system encounters a web service error upon saving edits. 

To recreate:
TMDL Strategies > Planting Trees > District 4 > 030005UT 
Create asbuilt
Save
web service error #2032 encountered and the asbuilt record will not save

**Comment by GraceAi** [comment]
Fixed the bug in web service. It was caused by the invalid value in "Submittal Number" field.

**Comment by BrittanyHuber** [comment]
Verified that it is working in KCI DEV
