### ISSUE TITLE
PHASE II - KCI DEV - Advanced Query - 6.11 - results are returned incorrectly 

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#167]
When selecting by advanced query, the results are returned incorrectly. In the feature manager, fields appear as their codes instead of their values. Also, information is in the incorrect fields. When selecting a feature, it does not populate any information in the attribute manager or zoom to a feature on the map. 

![image](https://cloud.githubusercontent.com/assets/8092133/6783033/faf3eaa8-d14d-11e4-9945-6ec298f7504b.png)

To recreate:
TMDL Strategies > Planting Trees
Advanced Query:
field name -  CNTY_CODE
operator -  "=" 
Unique Value - "03"

Incorrect fields for this example:
TMDL should be the populated with STRU_ID (ie. 030004UT)
TYPE should be populated with what what is in the WATERSHED field
SITE NAME should be populated with what is in the STATUS field
STATUS should be populated with what is in the TYPE field

Should appear as below:
![image](https://cloud.githubusercontent.com/assets/8092133/6783122/7ccc4d5e-d14e-11e4-9778-64273ba7ff9f.png)

***This problem occurs with other strategies as well.

**Comment by TaraF** [comment]
This has been fixed for both strategies and site selections. 

Please wait to test until notified.

**Comment by BrittanyHuber** [comment]
verified that this is working in KCI DEV
