### ISSUE TITLE
PHASE II - KCI DEV - Advanced Query - 6.11 - query does not clear upon new selection

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#168]
When the user creates an advanced query and adds it, the system retains the query until it is manually reset. If the user wants to switch strategies the query should be cleared. Also if the user wants to add a second statement, the filters should be reset. 

To recreate:
TMDL Strategies > Planting Trees
field name: CNTY_CODE
operator: = 
value: 03
switch strategies to > swales
the query statement is retained until the user selects "clear query"

**Comment by TaraF** [comment]
Fixed -- the advanced query builder is cleared out every time that the "Select By" changes -- whether it is strategy / siteselection or the list of types. The filters are also cleared once a new statement has been added to the bottom box -- as requested.

Please wait until notified to test.

**Comment by BrittanyHuber** [comment]
verified that this is working in KCI DEV
