### ISSUE TITLE
PHASE II - KCI DEV - Advanced Query - Web Service Error when selecting site selections

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#170]
They system encounters web service error #2032 when searching for site selections using advaced query. 

To recreate:
Site Selections > Trees
Adv Query: CNTY_CODE = 03
select any feature > web service error #2032

*this is for all site selections, assets do not return the error

**Comment by TaraF** [comment]
This has been resolved and redeployed to KCI dev. Please test.

**Comment by BrittanyHuber** [comment]
verified that this is working in KCI DEV
