### ISSUE TITLE
Phase II - SHA DEV - Versioning - 6.9.9.1 - will not submit version for QC

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#171]
Upon submitting a version for QC, the "Reviewer" column is not populated and the version does not appear in the versioning tab as ready for QC.  

To Recreate:
Create a version off of eGISW
Start editing the new version
Stop editing
Submit for QC
The system does not appear to have submitted the version for QC
When clicking the selection tab, error #2032 is encountered

**Comment by TaraF** [comment]
Note:  A GP process /script was missing from SHA.  A request has been sent to Jake Llyod to deploy it.  Will update status here when available.

**Comment by TaraF** [comment]
This is now working in SHA Dev. Please test.

**Comment by BrittanyHuber** [comment]
@TaraF - in the versioning tab, the only available tab is the Editor tab. The QC tab is missing even though I have admin rights.

**Comment by TaraF** [comment]
Brittany -- please test in KCI dev (Admin rights can now see QC Reviewer tab)

**Comment by BrittanyHuber** [comment]
verified that this is working in KCI DEV

**Comment by BrittanyHuber** [comment]
verified that this is working in SHA DEV
