### ISSUE TITLE
Phase II - SHA DEV - unable to save default when switching from pub to edit

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#172]
When switching versions using the version toggle in the upper right hand corner from Publication to Editing, the system defaults the Editing version to "eGISW" but does not allow the user to "Save" until they reselect an editing version. 

To Recreate:
using the toggle in the upper right hand corner switch to "Publication" 
save
switch version again to Editing
eGISW version is defaulted, however the Save button is grayed out and is not selectable until another version is selected from the Editing dropdown menu.

**Comment by TaraF** [comment]
This persisted in KCI dev.   Fixed -- the user is now forced to choose a version in Editing, before the Save button becomes enabled. 

Please wait to test until pushed and notified.

**Comment by BrittanyHuber** [comment]
verified that this is working in SHA DEV
