### ISSUE TITLE
Phase II - SHA DEV - Associating Documents - web service error when uploading document

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#173]
When attempting to add a document to a site selection site, the system encounters web service error #2038. 

To Recreate:
Site Selections > EFF BMP Site Selection
District 4 > Baltimore
030007 > documents tab 
add new document > browse to adobe pdf file > add
web service error #2038 

This issue seems to be with site selections only as it was not encountered with Assets.

**Comment by GraceAi** [comment]
Fixed. Changed document upload path to be "\shahqhisdfs1\oed_gis\TMDL Program\DocumentManagement\". Web config file in Web service needs to be updated.

**Comment by BrittanyHuber** [comment]
@TaraF unable to upload documents in SHA DEV

**Comment by TaraF** [comment]
please test again.  reference was missing from the config -- but has now been updated.

**Comment by BrittanyHuber** [comment]
verified that this is working in SHA DEV
