### ISSUE TITLE
Phase II - SHA DEV - system does not save review records added to features

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#174]
When the user adds a Site Visit record to a site selection feature, the system does not maintain edits upon selecting "save" within the results tab. 

To Recreate: 
Site Selection > EFF BMP Site Selection
District 4 > Baltimore 
0300002 > site visit
add test record
save on the editing toolbar in the results tab
the system does not maintain the new site vist record that was just added

**Comment by GraceAi** [comment]
Fixed. EFF_BMP_PLANNED_ID(not EFF_BMP_SELECTION_ID) should be associated to new site visit record.

**Comment by BrittanyHuber** [comment]
verified that this is working in SHA DEV
