### ISSUE TITLE
Phase II - SHA DEV - 6.27.2 - unable to edit general information in the stream limits tab

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#176]
When the user attempts to edit information in the field contained in the stream limits tab, the system does not allow edits to be made. 

To Recreate:
TMDL Strategies > Stream Restoration
District 4 > Baltimore
030006UR > General tab > Limit tab 
Station from, station to, length and general comments appear as though they are text input editable fields, however the system does not allow edits to be made.

**Comment by TaraF** [comment]
This persists in KCI dev.  Grace -- can you take a look?

**Comment by GraceAi** [comment]
Fixed on KCI dev.

**Comment by BrittanyHuber** [comment]
verified that this is working in KCI DEV.

**Comment by BrittanyHuber** [comment]
verified that this is working in SHA DEV
