### ISSUE TITLE
Phase II - SHA DEV - 6.28.3 - CBC Reduction tab is empty 

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#177]
The reduction tab for catch basin cleaning does not display any fields/information.

**Comment by GraceAi** [comment]
Unable to replicate this issue on KCI DEV...

**Comment by TaraF** [comment]
Unable to replicate on SHA DEV either -- I am seeing info displayed in the Reduction tab for CBC.  Please see screen cap below.  Can you provide a specific example?  It may be a data issue?

![image](https://cloud.githubusercontent.com/assets/4104464/7066399/4781ae42-de90-11e4-8e8a-5312203d752b.png)

**Comment by BrittanyHuber** [comment]
@TaraF - when testing again, it seems that there is a slight lag in the response time when switching between features while on the reduction tab. So the information appears, it just took a few extra seconds to load.
