### ISSUE TITLE
Phase II - SHA DEV - 6.30.1 - Editing - the system doesn not retain edits made to street sweeping segments

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#178]
When edits are made to the street sweeping plan segments tab, the system does not reatin the edits upon selecting "save" from the results tab. 

To Recreate:
TMDL Strategies > mechanical street sweeping
District 4 > Baltimore 
030001US > general > plan segments tab
change sweep type from type 3 to type 1 > save
the system does not maintain the edits

**Comment by GraceAi** [comment]
Unable to replicate this issue on KCI DEV...

**Comment by TaraF** [comment]
Unable to replicate in SHA DEV either -- this edit saved for me.  Brittany -- maybe we can walk through it together / screen share?

**Comment by BrittanyHuber** [comment]
@TaraF upon testing this again, it seems to be working in SHA DEV
