### ISSUE TITLE
Phase II - SHA DEV - 6.32 - the sysem does not allow the user to change BMP Type

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#179]
When the user attempts to change the BMP type, the system does not maintain the edits. 

To Recreate:
TMDL Strategies > District 5 
080503 
MDE BMP TYPE > edit from Swales to Sand Filter > Save
The system maintains Swales

**Comment by GraceAi** [comment]
SP "EditEffBmp" misses BMP_TYPE as the parameter.

**Comment by ehsan67** [comment]
@GraceAi  added

**Comment by GraceAi** [comment]
Fixed. Need to republish web service.

**Comment by BrittanyHuber** [comment]
verified that this is working in SHA DEV
