### ISSUE TITLE
Phase II - SHA DEV - potential tree sites display 1 contract, while the tab is actually null

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#180]
Possible DB Issue - 

TMDL Strategies > Tree Planting > site name 080215UT-A
Contract (1) > no contract associated
When a contract is added the indicator number displays 1 still. when a second contract is added the indicator number flashes (3) then goes to (2)

**Comment by GraceAi** [comment]
@BrittanyHuber, I can't find this strategy. Can you provide more information? Thanks!

**Comment by BrittanyHuber** [comment]
@GraceAi - the site is in district 5 - Charles County. This issue should persist with any of these tree sites with a status of "Proposed" or "Potential." It does not necessarily have to be the exact site I used as an example. If you still cant find one let me know! Thanks

**Comment by GraceAi** [comment]
@BrittanyHuber, I can't find a planting tree with a status of 'Potential' on KCI DEV. For the planting tree with a status of 'Proposed', it seems working.

**Comment by BrittanyHuber** [comment]
@GraceAi this is present in SHA DEV.

**Comment by TaraF** [comment]
Cannot find that SITE_NAME value in LUCHANGE_BMP in the database.  Can you be more specific about your selection process so we can replicate it exactly?  (You don't state a selection criteria -- district =? or county?)

**Comment by BrittanyHuber** [comment]
@TaraF I apologize, I thought I left the comment that it is District 5 > Charles county. Let me know if you cant find it and I will either find an different example or do a screen share.

**Comment by TaraF** [comment]
Grace -- I think the issue is when there is no contract associated, the count will still say (1) on the Contracts tab. It probably then causes an issue with the count when adding one.  I found one without a contract behaving in this way, that you could test in KCI dev:  

TMDL Strategies --> Planting Trees --> District 3
TMDL = 160104UT  (can just sort by the Contract column, it is the only empty one)

**Comment by GraceAi** [comment]
@ehsan67, for the example Tara provided(TMDL activity id is '1c514530-2724-4c2a-9741-e0f0849ed628'), the contract count returned is 1. But there is no contract number info for this contract. Can you take a look at database? Thanks.

**Comment by ehsan67** [comment]
Fixed. Please test it again.

**Comment by BrittanyHuber** [comment]
verified that this is working in KCI DEV

**Comment by BrittanyHuber** [comment]
verified that this is working in SHA DEV
