### ISSUE TITLE
Phase II - SHA DEV - Editing - Unable to upload photos 

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#181]
When attempting to upload a new photo to a site, the picture does not appear.

To Recreate:
TMDL Strategies > Stream restoration
Inspections > Inspection Details 
Select a photo to upload > save
the system does not display the photo, however it displays "Photo 1 of 1" as if there is a photo associated

**Comment by GraceAi** [comment]
Fixed. Changed photo upload path to be "\shahqhisdfs1\oed_gis\TMDL Program\DocumentManagement\". Web config file in Web service needs to be updated.

**Comment by BrittanyHuber** [comment]
verified that this is working in KCI DEV

**Comment by BrittanyHuber** [comment]
@TaraF unable to upload photos in SHA DEV

**Comment by TaraF** [comment]
Please test again.

**Comment by BrittanyHuber** [comment]
@TaraF - I am still unable to upload photos to sha dev.

**Comment by BrittanyHuber** [comment]
verified that this is working in SHA DEV

**Comment by BrittanyHuber** [comment]
Verified that this is working in PROD
