### ISSUE TITLE
Phase II - KCI DEV - 6.12.8 - edits do not appear in red in the feature manager

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#182]
When the user makes edits to a feature, the system does not present the text in the feature manager in the color red after the edit has been saved (during the specific session only)

To Recreate:
Start an editing session
TMDL Strategies > Tree Plantings
District 4
Select any tree site
Change the Site name
Save Edits
The changes are made in the feature manager, however they do not appear in the color RED.

**Comment by GraceAi** [comment]
@BrittanyHuber, is the edited text or the entire row's text supposed to be red?

**Comment by BrittanyHuber** [comment]
@GraceAi - the text row should be red in order to show that the feature was edited.

**Comment by BrittanyHuber** [comment]
verified that this is working in KCI DEV

**Comment by BrittanyHuber** [comment]
verified that this is working in SHA DEV
