### ISSUE TITLE
SHA PROD - site delete issue in attribute manager

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#186]
When a site is deleted, the attribute manager highlights the next site below the deleted site in red as if it were the site being edited. 

To recreate:
site selection > eff_bmp_site_selection
district 3
sort by SSID > delete site 1500001, SAVE
150004 highlights in RED

**Comment by BrittanyHuber** [comment]
Also this seems to happen on the SAVE - when a strategy asset is deleted a dialog appears that says the site has been deleted - the site that takes the spot in the attribute manager of the site that has been deleted does not appear in red until you save. this dialog box informing that the site has successfully been delete does not appear when deleteing site selection features.

**Comment by GraceAi** [comment]
Fixed the bug in clicking delete and save buttons. Added a confirmation box for site selection. Clicking delete button would directly delete the record. You don't need to click save again

**Comment by BrittanyHuber** [comment]
Verified that this is working in KCI DEV

**Comment by BrittanyHuber** [comment]
verified that this is working in SHA DEV

**Comment by BrittanyHuber** [comment]
verified that this is working in PROD
