### ISSUE TITLE
PHASE III - KCI DEV - Error Adding Stream Site Selection Feature

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#188]
When adding a stream site selection feature, the system returned the following IO Error

![image](https://cloud.githubusercontent.com/assets/8092133/7475412/72d1d22c-f315-11e4-8d2b-9cbf56fdf69d.png)

To Recreate:
Site Selections > Stream Site Selection
Enable Editing > Add
Select Stream Site Selection
Draw polyline
Next
Fill out the fields presented in the dialog box
Finish
IO Error encountered

**Comment by GraceAi** [comment]
Discussed with Dustin. KCI will change field "CO_ID" in the database to allow for Null values.

**Comment by BrittanyHuber** [comment]
@GraceAi - i am still encountering an error when adding stream site selection features.  ![image](https://cloud.githubusercontent.com/assets/8092133/7960709/8b9f5212-09d0-11e5-87cb-6c2bcad47503.png)

**Comment by GraceAi** [comment]
@BrittanyHuber, I told Ehsan yesterday. He is working on it.

**Comment by BrittanyHuber** [comment]
@ehsan67 - is this ready to be tested?

**Comment by GraceAi** [comment]
@BrittanyHuber, ready for test. Thanks!

**Comment by BrittanyHuber** [comment]
tested in KCI DEV and verified that this is working.
