### ISSUE TITLE
PHASE III - KCI DEV - Geometry Error Adding Features

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#189]
When adding a tree site selection feature the system does not retain geometry and returns the following error. 

![image](https://cloud.githubusercontent.com/assets/8092133/7475549/3a08bcd4-f316-11e4-9138-c3fdccb46f51.png)

To Recreate: 
Site Selection > Tree Site Selection
Add
Select Tree Site Selection > Next
Fill out the fields presented in the dialog box
Finish
The feature is added to the widget but the No geometry found error persists

**Comment by BrittanyHuber** [comment]
The two letter code added to the end of the 7 digit number does not get populated for any feature added
Pavement removal = UI
Stream Site Selection = UR
Tree Site Selection = UT
Wetland Site Selection = AW
EFF BMP Site Selection = NO LETTERS, just the number
EFF BMP Retrofit Site Selection = NO LETTERS, just the number
Excess Land Site Selection =  NO LETTERS, just the number
Outfall Stabilization Site Selection = UO

**Comment by BrittanyHuber** [comment]
No geometry data error also experienced with Wetland Site Selection, Pavement Removal Site Selection, Excess Lands Site Selection

**Comment by GraceAi** [comment]
I can't replicate this error for Tree Site Selection, Wetland Site Selection, Pavement Removal Site Selection or Excess Lands Site Selection. @BrittanyHuber, did you draw the geometry when creating the feature?

**Comment by BrittanyHuber** [comment]
@GraceAi - yes I drew the geometry when prompted to while adding the feature. Upon submitting the feature the error is returned. However the feature is created.

**Comment by johnshiu** [comment]
I have also tried to replicate this issue, but things appear to be creating properly without any geometry error message. @BrittanyHuber, maybe we can try creating a different editing version and seeing if it still occurs. Perhaps it be related to the specific version being edited?

**Comment by BrittanyHuber** [comment]
@johnshiu @GraceAi - when I first went through the process I populated all of the fields and upon selecting "finish" the system returned a mssage that the site selection feature was successfully added and all of the fields were populated, however it returned the "no geometry error" and the geometry was missing

When I go through the process now - I created a new version and went through the steps to add a pavement removal site selection feature. Upon selecting "finish" the feature is not added at all and the following error is returned...

![image](https://cloud.githubusercontent.com/assets/8092133/7566320/0ad634f2-f7c4-11e4-9078-e3c3d2787981.png)

**Comment by GraceAi** [comment]
@BrittanyHuber, Ehsan is adding the missing parameters in database. I will let you know when to retest. Thanks!

**Comment by BrittanyHuber** [comment]
tested in KCI DEV and verified that this is working.
