### ISSUE TITLE
Pavement Removal Site Selection (TMDL Widget)- Update Fields from Feature Manager-6.15

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#19]
Use the attached screen shot to update the Pavement Removal Site S
![pavement removal site selection](https://cloud.githubusercontent.com/assets/4129185/3218184/c690b14e-efe7-11e3-8956-8d59e2f37261.JPG)
election Attribute Manager Fields.

**Comment by ecomwu** [comment]
I've changed fields and committed my change to repository as well. Please test it later.

**Comment by dhenry-KCI** [comment]
Fixed
