### ISSUE TITLE
PHASE III - KCI DEV - Field Populating Errors

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#190]
Pavement Removal Site Selection - When presented with the list of fields to fill out when adding the feature, the system does not retain some of the edits upon submitting the feature. The system also does not automatically populate some of the fields that should be automatically populated. 

Does not populate: 
MS4 Jurisdictions 
4 Miles to Airport 
Imagery date

Were populated when creating the feature but it is not retained upon adding the feature:
Imagery Source 
Imagery Name
Length
Area 
Description
Begin Milepost
End Milepost
Removal Type

![image](https://cloud.githubusercontent.com/assets/8092133/7476759/b603ccfa-f31d-11e4-9b5a-881f99021b7b.png)

**Comment by BrittanyHuber** [comment]
MS4 and 4 miles to airport are not populated for any feature created (site selections and assets)

**Comment by BrittanyHuber** [comment]
site type and description are not maintained for any site selection feature

**Comment by GraceAi** [comment]
@Ehsan, can you add these missing parameters in AddPavementRemSiteSel? MS4 and 4 miles are probably data issue. Can you confirm?

**Comment by BrittanyHuber** [comment]
@GraceAi - imagery date is populated by the user, this should not be populated automatically

**Comment by BrittanyHuber** [comment]
tested in KCI DEV and it is working at this time.
