### ISSUE TITLE
PHASE III - KCI DEV - add/create buttons

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#191]
The system presents the user with two buttons to create a site selection feature, "Add" and "Create Str." The text "Create Str." should appear as "Pipeline" due to possible confusion with "Add."

**Comment by TaraF** [comment]
This has been changed. Please test.

**Comment by BrittanyHuber** [comment]
@TaraF - I am not seeing this button at all now 

![image](https://cloud.githubusercontent.com/assets/8092133/7746803/645b031a-ff83-11e4-9a2a-98bc1a530fac.png)

**Comment by BrittanyHuber** [comment]
tested in KCI DEV and it is fixed.
