### ISSUE TITLE
PHASE III - KCI DEV - Symbology should be the same when adding new feature

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#193]
When the user adds a new feature the geometry is displayed as a hollow outline of the feature. This should appear as a polygon with the fill color of the respective feature. 

Example:
New tree site seleciton feature added is displayed as a hollow outline
![image](https://cloud.githubusercontent.com/assets/8092133/7477884/de1ae424-f324-11e4-8990-eb7fdbc575f0.png)

Tree Site Selection feature that already exists has a green fill
![image](https://cloud.githubusercontent.com/assets/8092133/7477904/fdb26398-f324-11e4-8e0b-d8f2949ec08e.png)

**Comment by TaraF** [comment]
Tree Site Selection in the map service is only an outline of green around the polygon.  Planting Trees Strategies in the map service are the dark green filled polygon.  Add graphics appear to have a blue fill already, like Grace indicated. 

Please test again, and see if there is a disagreement in how the display should be.

**Comment by BrittanyHuber** [comment]
tested in KCI DEV and it is fixed.
