### ISSUE TITLE
PHASE III - KCI DEV - Site Selection ID's not populating correctly 

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#194]
When the user adds a feature, the Site Selection ID should be populated with a two digit letter (ie. UT) on the end of the 7 digit number (ie. 2010000UT).

![image](https://cloud.githubusercontent.com/assets/8092133/7478771/e3454eb6-f32a-11e4-9b95-3d3c8aaede5d.png)

The two letter code added to the end of the 7 digit number does not get populated for any feature added, and should be as follows:
Pavement removal = UI
Stream Site Selection = UR
Tree Site Selection = UT
Wetland Site Selection = AW
EFF BMP Site Selection = NO LETTERS, just the number
EFF BMP Retrofit Site Selection = NO LETTERS, just the number
Excess Land Site Selection =  NO LETTERS, just the number
Outfall Stabilization Site Selection = UO

**Comment by GraceAi** [comment]
@ehsan67, can you take a look at your sp? Thanks!

**Comment by ehsan67** [comment]
@BrittanyHuber  fixed in KCI DEV please test agian.

**Comment by BrittanyHuber** [comment]
@ehsan67 - same issue as #207 - seems to be populating with numbers starting in the 1000's instead of the next highest number

**Comment by ehsan67** [comment]
@BrittanyHuber  sorry I forgot to tell you , I reset the number, so it is normal to see it starts form 1000. Each Strategy Group (for example : Stream Restoration, Outfall, StreetSweeping and etc.) has its own counter which starts from 1000 and goes up

**Comment by BrittanyHuber** [comment]
tested in KCI DEV and verified that this is working
