### ISSUE TITLE
PHASE III - KCI DEV - IO Error when adding Swales 

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#195]
When the user attempts to add a Swale Asset, the system returns the following IO Error:

![image](https://cloud.githubusercontent.com/assets/8092133/7481551/b4097960-f33e-11e4-97d8-bb766653e103.png)

The feature is not added.

**Comment by GraceAi** [comment]
@BrittanyHuber, what was your input for this error?

**Comment by BrittanyHuber** [comment]
@GraceAi 
Add > Swales
120221 > Next
entered random values to populate each field for 3 and 4 > finish

**Comment by GraceAi** [comment]
@ehsan67,  In AddEffBmp, ESD_DEPTH, ACTUAL_DA_ACRES,  ACTUAL_IMPV_TREATED and PE_RAINFALL_TREATED are missing. Can you add them in the parameters?

**Comment by ehsan67** [comment]
@GraceAi  they are added

**Comment by GraceAi** [comment]
@BrittanyHuber, please test

**Comment by BrittanyHuber** [comment]
@GraceAi - I am still encountering errors when adding swales 

![image](https://cloud.githubusercontent.com/assets/8092133/7747431/5c697268-ff88-11e4-9851-4bfca501880d.png)

**Comment by GraceAi** [comment]
@BrittanyHuber, can you post the screenshots of your input. I can't replicate it.

**Comment by BrittanyHuber** [comment]
@GraceAi - I am unable to replicate. If I encounter this again I will repost. Thanks!

**Comment by BrittanyHuber** [comment]
tested in KCI DEV and verified that it is working
