### ISSUE TITLE
PHASE III - KCI DEV - Stru_ID's populating with the wrong 2 letter code

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#196]
![image](https://cloud.githubusercontent.com/assets/8092133/7499015/fbeabb04-f3f2-11e4-898d-777e6634a4c7.png)

Catch Basin Cleaning = UC
Outfall Stabilization = UO
Street Sweeping = US
Stream Restoration = UR
Pavement Removal = UI
Wetlands = AW
Trees = UT

**Comment by GraceAi** [comment]
@ehsan67, can you take a look at your stored procedures? Thanks.

**Comment by ehsan67** [comment]
@GraceAi  it might be old data, because I don't have "PU" at all in my code

**Comment by GraceAi** [comment]
@ehsan67,  your use strategyType to generate the last two letters. Strategy Type for tree is FPU.

**Comment by ehsan67** [comment]
@BrittanyHuber  fixed please text again

**Comment by BrittanyHuber** [comment]
tested in KCI DEV and verified that this is working
