### ISSUE TITLE
PHASE III - KCI DEV - Assets - For Credit Field 

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#197]
When adding a TMDL Strategy Asset, the system does not include "For Credit" as an option to fill out when adding the feature. Upon submitting the feature this field is automatically populated.

![image](https://cloud.githubusercontent.com/assets/8092133/7499179/ea894a1e-f3f3-11e4-9dc9-8230e11fce9e.png)

![image](https://cloud.githubusercontent.com/assets/8092133/7499200/00535448-f3f4-11e4-9719-cb3017258e74.png)

**Comment by GraceAi** [comment]
For credit value is populated based on status and county code in the back end. User is able to edit after that.
