### ISSUE TITLE
PHASE III - KCI DEV - Stream Restoration Issues

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#198]
When adding a stream restoration feature the Stream Name field is not maintained upon submitting the feature.

![image](https://cloud.githubusercontent.com/assets/8092133/7499300/b0ba4c10-f3f4-11e4-88e0-d9f3fcb0fa61.png)

Also, the system does not allow the user to add a stream limit - it is not a feature type, so it is not available as an option in the feature type drop down menu.

**Comment by GraceAi** [comment]
@ehsan67,  Stream Name is missing from the parameters in AddStreamRestoration. Can you add it?

**Comment by GraceAi** [comment]
@BrittanyHuber, user can add a stream limit after adding a new Stream Restoration. Should adding a stream limit function be available during adding a new Stream Restoration process?

**Comment by BrittanyHuber** [comment]
@GraceAi - the workflow can remain as it is now.

**Comment by ehsan67** [comment]
@GraceAi  added

**Comment by GraceAi** [comment]
Fixed. Need to update web service.

**Comment by GraceAi** [comment]
@ehsan67, Stream Name is still not populated. Can you check again?

**Comment by ehsan67** [comment]
@GraceAi  fixed

**Comment by GraceAi** [comment]
@BrittanyHuber, please retest.

**Comment by BrittanyHuber** [comment]
tested in KCI DEV and it is working
