### ISSUE TITLE
PHASE III - KCI DEV - Asset - Cannot Add Outfall Stabilization

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#199]
When adding an outfall stabilization, the user is prompted to enter a 3 digit code to filter the NPDES structure. Upon selecting a 3 digit code, the system does not filter any results.

![image](https://cloud.githubusercontent.com/assets/8092133/7499409/62c09d4c-f3f5-11e4-8018-8fe65030e00a.png)

Add > Outfall stabilization
enter 020, 041, 210 - all of these are two digit county codes followed by a number so they should return results

**Comment by GraceAi** [comment]
Data issue. Currently there is no data in npdes structure table.

**Comment by BrittanyHuber** [comment]
@GraceAi - i am still seeing an error when adding outfall assets. site selections are working fine at this point.

![image](https://cloud.githubusercontent.com/assets/8092133/7967617/23d0f446-09f9-11e5-83d9-f6cd7d599517.png)

**Comment by GraceAi** [comment]
@BrittanyHuber, which npdes structure number did you select?

**Comment by BrittanyHuber** [comment]
@GraceAi - 1000495.302

**Comment by BrittanyHuber** [comment]
tested in KCI DEV and verified that this is working.
