### ISSUE TITLE
PHASE III - KCI DEV - Street Sweeping Asset - Not Prompted to Add Geometry

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#200]
When attempting to add a street sweeping asset, the system does not prompt the user to add the geometry of the feature.

Add > Mechanical Street Sweeping 
Enter Activity information > next
Enter feature information > next 
Finish 
query service error returned - no geometry data found for this asset

**Comment by GraceAi** [comment]
Talked with Dustin. User won't draw geometry in the widget for a street sweeping asset.

**Comment by dhenry-KCI** [comment]
The user will not be able to add Street Sweeping Assets through the widget, but the user can add Actual Sweepings (this works).
