### ISSUE TITLE
PHASE III - KCI DEV - Unable to Add EFF BMP RETROFIT Asset

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#202]
EFF BMP RETROFIT is not a feature type included in the widget, so it is not included in the feature type drop down menu when attempting to add a feature.

**Comment by ehsan67** [comment]
@GraceAi  @TaraF  I wasn't sure who worked on that piece but widget is calling 
http://vm-city102/TMDL/api/Domains/GetStrategyNames?format=xml&isexisting=true&database=edit

As you see "IsExisting=true" which returns only the types that have been used in the database. To return all types you need to pass false to that parameter

**Comment by GraceAi** [comment]
@Ehsan @BrittanyHuber, which one is the EFF BMP RETROFIT Asset? What is the code?

**Comment by ehsan67** [comment]
@GraceAi  seems like Eff BMP retrofits are stored in EffBMP table. so you should use AddEffBmp
@dhenry-KCI  Does it sound right?

**Comment by dhenry-KCI** [comment]
@ehsan67 @GraceAi - Yes EFF_BMP Retrofits are stored in the EFF_BMP table.

**Comment by BrittanyHuber** [comment]
tested in KCI DEV and verified that this is working
