### ISSUE TITLE
PHASE III - KCI DEV - Acres Should Auto Populate

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#203]
When adding a either a tree site or pavement removal site selection or asset, the system should auto populate the acreages based on the geometry of the site. 

Asset - Credit Acres
Site Selection - Potential Credit Acres

**Comment by GraceAi** [comment]
@ehsan67, can you take a look at your stored procedures? Thanks.

**Comment by ehsan67** [comment]
I modified SPs to calculate and populate those values , for TreeSiteSelection, PavementRemovalSiteSelection , and all Lu_Change_BMP assets . @BrittanyHuber please test again and confirm if the result is right

**Comment by BrittanyHuber** [comment]
fixed.
