### ISSUE TITLE
PHASE III - KCI DEV - Incorrect Wetland Mast Type

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#204]
When adding a Wetland asset the only mast type available = urban tree planting 
- mast type should = WP

**Comment by GraceAi** [comment]
@ehsan67, can you take a look at your stored procedures? Thanks.

**Comment by ehsan67** [comment]
@BrittanyHuber  @GraceAi  What should be the Mast types for Wetland asset?

**Comment by GraceAi** [comment]
@Ehsan, currently in the program it is SW

**Comment by GraceAi** [comment]
Sorry, it is "SM"

**Comment by GraceAi** [comment]
@Ehsan, never mind. My answer was wrong.

**Comment by BrittanyHuber** [comment]
@ehsan I am looking into this right now, I will let you know shortly

**Comment by BrittanyHuber** [comment]
@ehsan - the mast type should be "WP" Wet Ponds & Wetlands

**Comment by ehsan67** [comment]
@BrittanyHuber  Fixed, please try again. @TaraF we need to copy "MAST_MDE_STRU" data to other environments (SHA prod, SHA dev)

**Comment by BrittanyHuber** [comment]
fixed.
