### ISSUE TITLE
PHASE III - KCI DEV - Pipelining Swales Issues

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#205]
When pipelining an eff bmp site selection into a swale and the site selection has more than 1 Planned BMP, the user may only want to choose 1. the way the system presents the option does not distinguish one planned bmp record from the other. the user will not know which one to select. There are also a few other errors during the pipelining process - which was unable to successfully complete. 

Site selection > eff bmp site selection
distrct 4 > harford > 1200005
Create Str. 
Swales > Next 
Next 
Then presented with the following:
![image](https://cloud.githubusercontent.com/assets/8092133/7500648/db41f192-f3fc-11e4-9ac9-8640cd81bda7.png)
Both are exactly the same (if the user only wants to choose 1 or the other they may not know which to chose)
Select both records
When assigning geometry the "Set Geometry" button goes gray at times (will activate eventually)
![image](https://cloud.githubusercontent.com/assets/8092133/7500699/48a81c16-f3fd-11e4-828b-207e27456967.png)
set geometries to both records 
construction purpose drop down menu is blank 
![image](https://cloud.githubusercontent.com/assets/8092133/7500756/a9986076-f3fd-11e4-9616-ce027164069c.png)
finished creating strategies
failed to create strategies
![image](https://cloud.githubusercontent.com/assets/8092133/7500784/ec589b1a-f3fd-11e4-8bb8-4f95c67b831d.png)
This error has to be selected several times before it goes away

**Comment by BrittanyHuber** [comment]
Unable to pipeline any site selection feature to an asset 

Also, Construction purpose dropdown menu is null for all feature types

**Comment by BrittanyHuber** [comment]
The failure to create strategies error that occurs ~5 times in a row. You have to click OK multiple times for the error message to go away. Each time you select OK, the background becomes more clear.

**Comment by TaraF** [comment]
See email about items.  For the Duplicate SSID review table, the geometry is now zoomed to when selecting an item in the list (clicking on a row in the datagrid), as requested.  

Also, Grace clarified what needed to be passed in for services, and the create appears to be working for EFF BMPs as well as non- EFF BMPs.  

Construction Purpose Dropdown menu issue -- i cannot really replicate it.  If there is a specific process where this is happening please provide details and i will try to replicate / fix.

**Comment by BrittanyHuber** [comment]
@TaraF - in this window the values still appear as coded values - due to space issue I think this is ok, what do you think?

![image](https://cloud.githubusercontent.com/assets/8092133/7748377/da9e8a02-ff91-11e4-8383-2719b091c4e0.png)

Also, I am still encountering construction purpose issue...
Site selection > eff bmp site selection
distrct 4 > harford > 1200005
Create Str. 
Swales > Next 
1200005UT > Next 
Step 3. select first option
![image](https://cloud.githubusercontent.com/assets/8092133/7748404/3dc031a8-ff92-11e4-86a7-819dfa6c8be9.png)
next
Set geometry > 120095 > next 
Construction purpose dropdown menu is null
Failed to create strategies (which has to be selected twice before it disappears)

**Comment by TaraF** [comment]
Coded values are good at this point -- you are right, full name will be cut off anyways due to space.

Construction purpose issue should be fixed -- all dropdown values should be available.  Please test other cases also.  

Please wait to test until notified of push.

**Comment by BrittanyHuber** [comment]
tested in KCI DEV and verified that this is working.
