### ISSUE TITLE
PHASE III - KCI DEV - IO Error

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#206]
When adding a tree site selection feature the following error is returned 
![image](https://cloud.githubusercontent.com/assets/8092133/7501409/9e9e9998-f401-11e4-957d-219101462fa2.png)

Pavement removal site selection 
![image](https://cloud.githubusercontent.com/assets/8092133/7501472/2ba87e6c-f402-11e4-9835-8f0869d4a11a.png)

Wetland Site Selection
![image](https://cloud.githubusercontent.com/assets/8092133/7501501/4f5f2b26-f402-11e4-9089-a712c91b7479.png)

**Comment by GraceAi** [comment]
Fixed. need to update flex.

**Comment by BrittanyHuber** [comment]
tested in KCI DEV and verified that this is working
