### ISSUE TITLE
KCI DEV - Related TMDL Features Populating Incorrectly

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#209]
In the Admin tab select contract AT5025282. The fields in the related features tab are not populated correctly

![image](https://cloud.githubusercontent.com/assets/8092133/7502955/c11a94de-f40d-11e4-902d-0b826e2a1f1a.png)

**Comment by TaraF** [comment]
This is fixed, please test.

**Comment by BrittanyHuber** [comment]
@TaraF - Type and Status are still populating as the coded values. 

![image](https://cloud.githubusercontent.com/assets/8092133/7747767/c1369272-ff8b-11e4-9dd0-7f1f57513572.png)

**Comment by TaraF** [comment]
Change is made -- will cut off text due to space issue.

Please wait to test until notified of push.

**Comment by BrittanyHuber** [comment]
tested in KCI DEV and verified that this is working
