### ISSUE TITLE
IO Error (TMDL Widget) Feature Manager

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#21]
If the user filters based on strategy or site selection then adds a geography filter and clicks "select" to review the results, the following error message will appear when the user selects certain records in the feature manager:
IO Error
The Asset Editor has encountered a web service error.
ioError:Error #2032
The error message seems to occur on records that have identical SS_IDs (EFF_BMP SIte Selection)

To recreate error:
Select By : Site Selections then Efficiency BMP Site Selection
12 Digit Watershed = 021308020297

IN feature manager select an SS_ID record = 0300610

![io_error](https://cloud.githubusercontent.com/assets/4129185/3219430/a4064f9a-eff5-11e3-963e-b7a6b7d590c0.JPG)

**Comment by dhenry-KCI** [comment]
Ehsan, 
We have discuss this issue in several different workflows. Just be aware.

**Comment by ehsan67** [comment]
it is because of duplicate SSID

**Comment by dhenry-KCI** [comment]
Known issue. we can re-evaluate with new data.
