### ISSUE TITLE
Active Editing Buttons Outside an Edit Session

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#210]
Tara,
As we discussed, there are several edit buttons that are active outside an edit session since we had a phased release allowing editors to add inspections, photos, etc before full versioning was in place. The following are locations within the widget where the user is allowed to add/delete items outside an edit session. Please disbale the add/Delete button in all locations when the user is not in an active edit session.
- Inspections (Add/Delete) - All Inspections
- Inspection Detail (Add/Delete)- Streams Only
- Stream Limit (Add/Delete) - Streams Only
- LUC_Practice (Add/Delete) - LU_CHANGE BMP Only
- Associate New Contract - All Features
- Add New Document - All Features
- As-Built (Add/Delete) - All Strategies
- Plat (Add/Delete) - All Features
- Actual Sweep - (Add/Delete) Street Sweeping
- Upload Photo - All 
- Site Visits (Add/Delete) - All Site Selection
- Agency Reviews (Add/Delete) - All Site Selections

**Comment by TaraF** [comment]
This is fixed, please test.

**Comment by BrittanyHuber** [comment]
@TaraF the following are still active:

Inspections (Delete) - All Inspections
Inspection Detail (Add/Delete)- Streams Only
Stream Limit (Delete) - Streams Only
LUC_Practice (Delete) - LU_CHANGE BMP Only
Upload Photo - All
Actual Sweep - (Delete) Street Sweeping
Site Visits (Delete) - All Site Selection
Agency Reviews (Delete) - All Site Selections
As-Built (Delete) - All Strategies
Plat (Delete) - All Features

**Comment by TaraF** [comment]
Brittany -- let's go over these when you have a chance.   Thanks!

**Comment by TaraF** [comment]
Fixed.  Please test for both non-editing and editing.

**Comment by BrittanyHuber** [comment]
tested in KCI DEV and verified that this is working
