### ISSUE TITLE
PHASE III - SHA DEV - fields need to be removed from ADD process

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#214]
When adding new features the system prompts the user to fill out certain fields that it will actually update for the user automatically regardless of the user input. For example, the user is required to populate the county and district fields when adding a feature. However, the system will override the user populated values and populate automatically based on the geometry. So if the user draws the geometry in Baltimore county district 4 and then populates the county and district fields as Montgomery district 3, the system will populate them as Baltimore, district 4 based on the geometry. The fields listed in the table below should be removed from the add feature process in the "Enter Feature Information" step:

![image](https://cloud.githubusercontent.com/assets/8092133/8089327/3c720860-0f75-11e5-9f35-8c33472fba69.png)

**Comment by GraceAi** [comment]
Fixed. Need to update flex.

**Comment by BrittanyHuber** [comment]
tested in SHA DEV and verified that the fields were removed
