### ISSUE TITLE
PHASE III - SHA DEV - fields not populating correctly

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#215]
A few fields are not working properly when adding a new feature:

**Pavement removal site selection** - _Area (FT) field_ - should populate automatically based on geometry when adding a new feature
**All Features (site selection and assets)** - _Bay Shed Segment field_ - does not populate. should populate automatically based on overlay information
**EFF_BMP Retrofit site selection** - _Site Type field_ - drop down menu presents the wrong information. Options given are excess lands and potential wetlands
**Outfall Assets** - _TMDL Structure ID field_ - is being populated with the NPDES number (1100041.001) instead of the 6 digit TMDL STRU_ID followed by the two letter structure code "UO" (EX: 161000UO)

**Comment by GraceAi** [comment]
@BrittanyHuber, in EFF_BMP Retrofit site selection, what is the correct site type field information?

**Comment by BrittanyHuber** [comment]
@GraceAi - I apologize that is correct. No changes need to be made for EFF_BMP_RETROFIT site selection.

**Comment by ehsan67** [comment]
@BrittanyHuber  Pavement removal site selection : Is it simply the geometry Area in ft?
All Features (site selection and assets) : is it geometry Area in ft?
Outfall Assets : There isn't TMDL_STRUCTURE_ID is the table. it is called NPDES_STRUCTURE_ID. Is that right?

**Comment by BrittanyHuber** [comment]
@ehsan67 - pavement removal site selection is the geometry area in FT. 

All Features (site selection and assets): Bay shed segment is called CBSEG_58 in the database

Outfall Assets: the TMDL ID should be the "STRU_ID" field from the OUTFALL_STABILIZATION table in the database.

**Comment by ehsan67** [comment]
Pavement removal site selection => unable to re generate
Outfall Assets - TMDL Structure ID field  => fixed
All Features (site selection and assets) - Bay Shed Segment field  => @GraceAi  Can you check the service ? I checked the stored procedure and looks like it is populating  the field  "CBSEG_58"

**Comment by GraceAi** [comment]
Pavement removal site selection => AREA_FT is not populated automatically. @ehsan67, do you need a fiddler session?  
All Features (site selection and assets) - Bay Shed Segment field => It is auto populated for every feature on KCI DEV. @BrittanyHuber, can you double check on SHA DEV?

**Comment by BrittanyHuber** [comment]
@GraceAi - you are right. I double checked in SHA DEV and the only one that doesn't seem to be working in outfall stabilization.

**Comment by GraceAi** [comment]
@BrittanyHuber, I tested outfall stab and it seemed to be working. Bay Shed Segment was populated.

**Comment by ehsan67** [comment]
@GraceAi @BrittanyHuber  I made a change in KCI DEV, please test for Pavement Removal Site Selection

**Comment by BrittanyHuber** [comment]
@GraceAi - I am sorry, I was adding features that are outside of the 11 NPDES counties. So I think that is why they were not populating.

**Comment by BrittanyHuber** [comment]
@ehsan67 - the area (ft) field should be square feet. it looks like it's populating acres (the same value as potential credit acres)

**Comment by ehsan67** [comment]
@BrittanyHuber  please test again , I changed it.

**Comment by BrittanyHuber** [comment]
@ehsan67 - tested and it is working, thanks!

**Comment by BrittanyHuber** [comment]
tested in SHA DEV and it is fixed
