### ISSUE TITLE
PHASE III - SHA DEV - remove street sweeping from ADD process

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#216]
When searching by All TMDL Strategies and the user selects Add, a list of all available feature types to add is presented in the drop down menu. Mechanical Street Sweeping needs to be removed from this list. 

Select by: Strategies > All TMDL Strategies
Filter By: Geography > District 4
OK
Add
Select feature type > Mechanical Street Sweeping is available. Needs to be removed.

**Comment by GraceAi** [comment]
Fixed. Need to update flex

**Comment by BrittanyHuber** [comment]
tested in SHA DEV and verified that this is working
