### ISSUE TITLE
Efficiency BMP Site Selection (TMDL Widget) - add fields to attribute manager

### ISSUE THREAD

**Issue by rmeitl** [dhenry-KCI/TMDL-_Tracking-Widget#22]
Fields are missing in attribute manager. The starred fields are missing:

_Site Selection ID_   (SS_ID)
_Type_  (needs to display type of site selection)
Site Status
Source
Site Type
_Prime Consultant_   (CONSULTANT_ID)
Description
etc. (The rest are ok)

**Comment by ecomwu** [comment]
Prime Consultant is not listed in requirement document section 6.19. Do we need it?
And for other fields, they are all displayed

**Comment by dhenry-KCI** [comment]
Maggie,
Yes please add Prime Consultant <EFF_BMP_SITE_SELECTION.Consultant_ID>

**Comment by ecomwu** [comment]
I've added Prime Consultant to this selection and committed the changes. Please test it later.
