### ISSUE TITLE
Efficiency Planned BMP SIte Selection (TMDL Widget) - Update Fields -6.19.2

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#23]
Update the following fields within the Efficiency Planned BMP tab in the Attribute Manager:
Rename the following fields:
Engineer Parameter should be renamed "Engineering Parameter (Acres)"
Enviro. Site Design Volume Depth should be renamed "Enviro. Site Design Volume"
Run-off Volume Depth should be renamed "Runoff Volume"
Impervious Area Treated should be renamed Area Treated. IT should be pulling data from the  <AREA_TREATED> field within EFF_PLANNED_BMP

Please move the SHA BMP Type field to the top of the list within the EFF_Planned BMP tab

**Comment by ecomwu** [comment]
I've renamed those fields, moved SHA BMP Type to the top of EFF_Planned BMP tab , and committed my change to repository as well. Please test it later.

**Comment by dhenry-KCI** [comment]
Fixed
