### ISSUE TITLE
Efficiency Planned BMP_DA (TMDL Widget)- Attribute Manager tabs

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#24]
When the user selects an Eff_Bmp SIte Selection record in the feature Manager the record appears in the Attribute Manager below with the following tabs:
Efficiency BMP- Planned BMP- Planned BMP DA
The widget correctly associated the Planned BMP to the Efficiency BMP, but if multiple Planned BMPs are available the  widget does not correctly relate the Planned BMP DA to the correct PLanned BMP.

TO recreate:
Select BY: Site Selection and Efficiency BMP Site Selection
County = Cecil
12 Digit Watershed = 021306030372
Select feature 0700007

**Comment by ecomwu** [comment]
I've fixed this issue and committed my change to repository as well. Please test it later.

**Comment by dhenry-KCI** [comment]
Fixed
