### ISSUE TITLE
Efficiency BMP Retrofit Site Selection (TMDL Widget) - field in attribute manager

### ISSUE THREAD

**Issue by rmeitl** [dhenry-KCI/TMDL-_Tracking-Widget#25]
Update alias 'SHA BMP Number' to 'SHA SWMFAC Number' and data should be pulling from SWMFAC.SWM_FAC_NO (6 digit id. Similar in format to: 060021), not NPDES_FACILITY_ID (which is a guid).

**Comment by ecomwu** [comment]
Ehsan, I've checked the service, SWM_FAC_NO is not included in the data return. You can check it by following link:
http://vm-city102/TMDL/api/SiteSelections/GetEffRetrofitGeneralInfo?version=eGISW&ssid=1600005

**Comment by ehsan67** [comment]
it is included in the result @ecomwu

**Comment by dhenry-KCI** [comment]
Fixed
