### ISSUE TITLE
Landuse Change BMP - Trees, Wetlands, Pavement Removal (TMDL Widget) - Acceptance Letter Field

### ISSUE THREAD

**Issue by rmeitl** [dhenry-KCI/TMDL-_Tracking-Widget#27]
6.26

Acceptance Letter field was updated and now has a domain assigned to it. This field should have a drop down using D_Accept_letter instead of being text input.

**Comment by ecomwu** [comment]
I've fixed this issue and committed the chagne. Please test it later.

**Comment by dhenry-KCI** [comment]
The acceptance letter field for Trees, Wetlands, and Pavement Removal is not being displayed as a dropdown using D_Accept_letter

**Comment by ecomwu** [comment]
I've changed Acceptance Letter field to dropdown using D_Accept_Letter. Please test it again. thanks!
