### ISSUE TITLE
Stream Restoration (TMDL Widget) - Stream Use

### ISSUE THREAD

**Issue by rmeitl** [dhenry-KCI/TMDL-_Tracking-Widget#28]
6.27

Stream Use in the attribute manager should reference field: STREAM_RESTORATION.STREAM_USE. The field in the database is null, so nothing should be returned in the attribute manager for that field. Currently the service is showing the guid for Stream Site Selection ID.

**Comment by ecomwu** [comment]
I've fixed it and committed the change. Please test it later.

**Comment by rmeitl** [comment]
Can you also apply this fix to Step Pool Stormwater Conveyance asset as well, please. Thanks!

**Comment by ecomwu** [comment]
once the selection service is changed, it will apply to all types of strategy selection. Then this issue will be gone.

**Comment by dhenry-KCI** [comment]
Fixed
