### ISSUE TITLE
Stream Restoration- (TMDL Widget)- Site Name in Feature Manager-

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#29]
The Site name is not being displayed in the Feature Manager for Stream Restoration.

To Recreate:
Select by =Strategies then Stream Restoration
County = Montgomery

USer should see a site name = PB-37

**Comment by ecomwu** [comment]
It relates to selection service. SITE_NAME are all null in feature manager. Tara/Ehsan, could you take a look at this issue?

**Comment by rmeitl** [comment]
This SITE_NAME is also an issue in Step Pool Storm Conveyance.

**Comment by dhenry-KCI** [comment]
Site Name appears correctly in the Feature Manager.
