### ISSUE TITLE
SELECTION- TMDL WIDGET- Shop Filter

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#3]
When the user initially filters by DISTRICT and COUNTY, the available SHOPS within that COUNTY are filtered. But, if the user changes the DISTRCT filter, the COUNTY will update with the appropriate COUNTY's for that DISTRICT but the SHOPS filter will not update.

**Comment by TaraF** [comment]
Shop is based on County selection; I have reset the Shop to show no values until a County is selected.  If District is selected again-- County will reset --Shop will show nothing until user selects a County.

**Comment by dhenry-KCI** [comment]
Fixed
