### ISSUE TITLE
Site Selection Documents tab (TMDL Widget) - attribute manager

### ISSUE THREAD

**Issue by rmeitl** [dhenry-KCI/TMDL-_Tracking-Widget#30]
6.21
Site selection features do not display any records in the documents attribute manager, even though the sites have one or more documents.

Site selection documents should mimic the document results for TMDL Strategies:

![egis1](https://cloud.githubusercontent.com/assets/7804977/3302644/6854b0ee-f636-11e3-9c06-989dd6ced853.png)

**Comment by ecomwu** [comment]
Ehsan, could you provide me a specific selection which has document information data return then I can test it on my end?

**Comment by ecomwu** [comment]
I've changed the code and committed already. Please test it later.
