### ISSUE TITLE
TMDL Select by Form (TMDL Widget) - All Strategies

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#31]
When the user selects by : TMDL Strategies , All Straegies

Then selects District 2 (error also occurs when the user Selects District 7) the follwing error appears:
![io_error_new](https://cloud.githubusercontent.com/assets/4129185/3302822/580eb9f8-f638-11e3-9287-1cb9001a8d75.JPG)

**Comment by ehsan67** [comment]
fixed
