### ISSUE TITLE
TMDL Strategies (TMDL Widget) - 6.12.1 Decode 'Status' field in the Selection Manager 

### ISSUE THREAD

**Issue by rmeitl** [dhenry-KCI/TMDL-_Tracking-Widget#32]
6.12.1
Use D_Status in the all_domains table to decode the Status field in the selection manager for all TMDL Strategies.

**Comment by ecomwu** [comment]
I've changed the code and committed to repository. Please test it later.

**Comment by dhenry-KCI** [comment]
Fixed
