### ISSUE TITLE
PlantingTrees Strategy (TMDL Widget) - 6.26 - General tab in attribute manager error

### ISSUE THREAD

**Issue by rmeitl** [dhenry-KCI/TMDL-_Tracking-Widget#33]
6.26
Occasionally a record will give the following error and not show results in the general attribute manager.

I isolated the problem and it seems to only happen when a Tree strategy has one or more documents associated with it.

![egis2](https://cloud.githubusercontent.com/assets/7804977/3303257/5a38f068-f63d-11e3-9853-fcbf3f8c43a0.png)

**Comment by ehsan67** [comment]
fixed
