### ISSUE TITLE
Street Sweeping Activity- (TMDL- WIDGET)-6.30.6

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#34]
No results are returned when the user select a Street Sweeping Plan and attempts to view the Street Sweeping activity, by clicking the Actual Sweep tab on the left side the screen (test data was added to check this functionality)

TO recreate- Select by TMDL Strategies, Mechanical Street Sweeping , Filter by District 3.

**Comment by ecomwu** [comment]
I've changed the code and committed to repository already.
Please test it later.

**Comment by dhenry-KCI** [comment]
Fixed
