### ISSUE TITLE
Outfall Stabilization- (TMDL- Widget)- Major Outfall and Feature Type Fields- 6.31.1

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#35]
In the Attribute Manager, Outfall stabilization features, the FEATURE TYPE field(remove the "s" from Feature Types in attribute manager) should pull records from domain D_STRUCT_Type. Within the Major Outfall field, values should be pulled from domain D_BooleanValues.- BOTH OF THESE VALUES SHOULD BE DECODED.

The relationship between Outfall Stabilization and Structures is outlined in requiremnt 6.31.1

**Comment by dhenry-KCI** [comment]
Maggie,
Its looks like the MAJ_OUTF field has a domain code of 1 (true) or 2 (false). To decode this domain use D_BooleanValues and not D_Boolean_Value- The current value being displayed in the MAJ_OUTF field is "OF"

**Comment by ecomwu** [comment]
I thought we need to add new domain service to decode it. currently, we only have D_Boolean_value @ehsan67

**Comment by dhenry-KCI** [comment]
Maggie,
On our end we do have a second domain of d_BooleanValue. I will talk to Ehsan.

**Comment by ecomwu** [comment]
I've completed the changes and committed already. Please test it later

**Comment by dhenry-KCI** [comment]
Fixed
