### ISSUE TITLE
EFF_BMP general information (TMDL Widget) - 6.32 Fields and Attributes

### ISSUE THREAD

**Issue by rmeitl** [dhenry-KCI/TMDL-_Tracking-Widget#36]
6.32
--For field 'TMDL BMP Type' - the Field description is missing in the general attribute manager. Also decode its domain D_BMP_Activity

--Update field description 'SHA BMP Number' to 'SHA SWMFAC Number' for consistency with our site selection swmfac numbers.

--Four Mile Vicinity Airport - decode domain: D_BooleanValues

**Comment by ecomwu** [comment]
I've changed the program and committed the code. Please test it later.

**Comment by dhenry-KCI** [comment]
Fixed
