### ISSUE TITLE
TMDL Activity for Strategy Assets (TMDL Widget) - 6.33D - fields/attributes

### ISSUE THREAD

**Issue by rmeitl** [dhenry-KCI/TMDL-_Tracking-Widget#37]
6.33D
--'Business Plan Year' year in the activity attribute manager is missing data. Should use field BPIS_YR

--'Offices' field in the activity attribute manager is missing data. Should use field OFFICE and decode domains D_Office.

--For Credit - decode value from all_domains D_Boolean_Value

**Comment by ecomwu** [comment]
I've changed program and committed changes. Please test it later.

**Comment by dhenry-KCI** [comment]
Fixed
