### ISSUE TITLE
TMDL Strategies Inspections (TMDL Widget) - 6.36-6.36.4

### ISSUE THREAD

**Issue by rmeitl** [dhenry-KCI/TMDL-_Tracking-Widget#38]
Currently all inspection tabs have 'Stream Condition' as the first field which is incorrect for other BMP Types.

Update the field name to 'Inspection Status'

**Comment by ecomwu** [comment]
I fixed this issue. Please test it later

**Comment by dhenry-KCI** [comment]
Fixed
