### ISSUE TITLE
Tree Strategies - Inspections (TMDL Widget) - 6.36.1 - fields/attributes

### ISSUE THREAD

**Issue by rmeitl** [dhenry-KCI/TMDL-_Tracking-Widget#39]
6.36.1
--First field is Stream Condition - should be 'Inspection Status' and pull data from field: ASSESS_CONDITION using D_BMP_Condition domain

--Missing the following fields:
Number of Shrubs <NUM_SHRUB>
Trees < 2 inches at Breast Height <TREES_LESSTHAN_2iN_ATBH>
Trees > 2 inches at Breast Height <TREES_GREATERTHAN_2IN_ATBH>
Total Tree Count <TOTAL_TREE_COUNT>
<PER_GREATERTHAN_2IN_ATBH>
Accurate Site Boundary <SITE_BOUNDARY_ACCURATE>
Site Boundary Comment <SITE_BOUNDARY_COMMENT>
Total Trees Per Acre <TOTAL_TREES_PER_ACRE>
Remediation Candidate <REMEDIATION_CANDIDATE> D_Boolean_Value

--Functioning - should update field description for tree inspections to 'Acceptable Site' - Should pull data from field ACCEPT_SITE using D_Boolean_Value domain

--General Comments - Should pull data from COMMENTS field

**Comment by ecomwu** [comment]
I've fixed this issue. Please test it later

**Comment by dhenry-KCI** [comment]
Fixed
