### ISSUE TITLE
SELECTION- (TMDL WIDGET) Filters

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#4]
If the user accidentally selects a DISTRICT and would rather filter by COUNTY, there is no way to remove the selection without doing one of the following:
1. Clicking the Reset button- which will reset all filters including the SELECT BY filters at the top OR
2. Selecting a different DISTRICT

**Comment by TaraF** [comment]
Per our discussion, the reset button now only clears and resets the filters grid, and does not effect the select by type and name.  Please review after next release.

**Comment by dhenry-KCI** [comment]
Fixed
