### ISSUE TITLE
EFF_BMP Strategy Inspections (TMDL Widget) - 6.36.4

### ISSUE THREAD

**Issue by rmeitl** [dhenry-KCI/TMDL-_Tracking-Widget#40]
'Stream Condition' field should be labeled 'Inspection Status' and pull data from ASSESS_CONDITION with domain D_BMP_Condition

**Comment by ecomwu** [comment]
I've fixed it and committed changes. Please test it later.

**Comment by dhenry-KCI** [comment]
Fixed
