### ISSUE TITLE
Selection Filters (TMDL-Widget)- Accordion Header Dynamic Text- 6.11.4

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#42]
Requirement 6.11.4 states that the system will display dynamic text within the accordion headers that indicate if a filter has been applied. 

I enter my select by and filter values and then click "Select" there is no indication that a filter has been applied.

**Comment by TaraF** [comment]
I believe this requirement was dropped -- please see meeting notes.  I will also re-forward my email regarding the updates made to the UI based on the meeting notes, which may not be reflected in the current requirements yet.
