### ISSUE TITLE
Results Tab (TMDL- Widget)- Site Selection Features

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#43]
When the user is filtering by Site Selection features, The Asset Report and Create Assets  under the feature manager on the results tab should be updated to read the following:
Site Report (formerly Asset Report)
Create Site (formerly Create Assets)

**Comment by ecomwu** [comment]
I've fixed it and committed the changes. Please test it later.

**Comment by dhenry-KCI** [comment]
Fixed
