### ISSUE TITLE
Stream Restoration (TMDL-WIDGET) - Attribute Manager- 6.72.2

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#44]
In Stream Restoration under the General Tab, Stream Limits tab can we add a field called , "Current Condition". This field will be populated where STREAM_RESTORATION.Stream_Rest_ID =STREAM_INSPECTION.Stream_Rest_id (grab the most current inspection date) then where STREAM_INSPECTION.Stream_Insp_ID = STREAM_INSPECTION_DETAILS.Stream_Insp_ID then where STREAM_INSPECTION_DETAILS.Restoration_Limits_ID = STREAM RESTORATION_LIMITS.Stream_Rest ID.

**Comment by ehsan67** [comment]
It is ready , @ecomwu  Maggie, please add it to the UI

**Comment by ecomwu** [comment]
I've added it and committed the changes. Please test it later

**Comment by dhenry-KCI** [comment]
Looks great. Fixed
