### ISSUE TITLE
Stream Restoration Inspection (TMDL-Widget)- Stream Inspection Details- 6.36

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#45]
The stream Inspection details tab under Inspections the Attribute Manager is missing the following fields:
Restoration Type (STREAM_INSPECTION_DETAILS.Restoration_Limits_ID= STREAM_RESTORATION_LIMITS.Restoration_Limits_ID, then where STREAM_RESTORATION_LIMITS.Restoration_LImits_ID =STREAM_RESTORATION_TYPES.REstoration_limits_ID- THIS WILL BE A 1:M relationship. Grab all associated Restoration Types, and separate with a comma).
Assess Condition (STREAM_INSPECTION_DETAILS.Assess Condition)
Gen_Com(STREAM_INSPECTION_DETAILS.Assess_Condition)

**Comment by ecomwu** [comment]
I've fixed it and committed the changes. Please test it later.

**Comment by dhenry-KCI** [comment]
Maggie, the above fixes are correct, but we need to make a few changes under the Insp. Details tab-
1. The Station_from field is pulling in the incorrect value. Currently it is displaying the REST_LENGTH value in STEAM_RESTORATION_LIMITS table
2. The Station_TO field is pulling in the incorrect value. Currently it is displaying the STATION_FROM value
3. The General Comments field in the widget, is currently blank and should be pulling values from GEN_COm field in Stream Restoration Limits table.

**Comment by ecomwu** [comment]
I've changed those three fields with correct value. Please test it later. Thanks.

**Comment by rmeitl** [comment]
Two more things with the comments field that I noticed besides the Station_From field:

--Condition Comments should pull data from field: STREAM_INSPECTION_DETAILS.GEN_COM

--General Comments field should pull data from field: STREAM_RESTORATION_LIMITS.GEN_COM

![untitled5](https://cloud.githubusercontent.com/assets/7804977/3528100/c325efe0-078b-11e4-9f65-ac2c83557e1c.jpg)

**Comment by ecomwu** [comment]
I've changed those comments fields under inspection details tab:
- Condition Comments: pull date from STREAM_INSPECTION_DETAILS.GEN_COM
- General Comments: pull data from STREAM_INSPECTIONS_DETAILS.RESTORATION_LIMIT.GEN_COM

Please test it later.

**Comment by rmeitl** [comment]
One last thing and I think Streams details are done. 

The field 'Plan Achieved' is not related to streams and can be removed.

**Comment by ecomwu** [comment]
Actually, it's my fault to put the wrong display name for that field, it should be "Overall Inspection performance" in inspection details tab. but the data is same as the Inspection tab's field "Functioning".
Do we still need to delete it?

**Comment by rmeitl** [comment]
If it's the same data that is for the field Functioning, I think we should be ok to delete it. Does this make sense @dhenry-KCI  ? I'll let him make the call though :)

**Comment by dhenry-KCI** [comment]
Yeah we can delete.
