### ISSUE TITLE
EFF BMP (TMDL-Widget) Missing Fields - 6.32

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#47]
Please create services and/or add the following fields:
Actual Drainage Area (Acres) < ACTUAL_DA_ACRES
Actual Impervious Treated <ACTUAL_IMPV_TREATED>
Targeted Rainfall <PE_RAINFALL_TREATED>

**Comment by ehsan67** [comment]
service returns those fields @ecomwu

**Comment by ecomwu** [comment]
I can't find Targeted Rainfall @ehsan67

**Comment by ehsan67** [comment]
we have PE_RAINFALL_TREATED . @dhenry-KCI  is it  the field?

**Comment by dhenry-KCI** [comment]
Yes PE_RAINFALL_TREATED is the correct field.

**Comment by ecomwu** [comment]
I've added those three fields to EFF BMP type selection. Please test it later. Thanks!
