### ISSUE TITLE
Contracts - (TMDL-Widget)- Contract Fields -6.34

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#48]
Please add the following services and fields to the vertical Contracts tab.
PE Start Date <PE_START_DATE>
PE End Date <PE_END_DATE>

**Comment by ehsan67** [comment]
service returns those fields . @ecomwu

**Comment by ecomwu** [comment]
I've added those fields under Contract fields and committed the changes. Please test it later.

**Comment by dhenry-KCI** [comment]
Fixed
