### ISSUE TITLE
EFF BMP (TMDL-Widget) Modify Fields- 6.32

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#49]
Please make the following changes to EFF_BMP fields:
TMDL BMP TYPE is displaying the correct field, but the field name is not displayed. See attached image. Also decode the Value field (D_BMP_ACTIVITY)

Update Runoff Volume field to display Runoff Depth
![missing field](https://cloud.githubusercontent.com/assets/4129185/3316182/1609fe64-f700-11e3-8b06-11549f041c3b.JPG)

**Comment by ecomwu** [comment]
I've fixed it and committed the changes already. Please test it later.

**Comment by dhenry-KCI** [comment]
Fixed
