### ISSUE TITLE
SELECTION - FILTERS (TMDL WIDGET)

### ISSUE THREAD

**Issue by rmeitl** [dhenry-KCI/TMDL-_Tracking-Widget#5]
6.11.10
When you **only select a 6 Digit Watershed, the 8 Digit Watershed and 12 Digit Watershed does not filter.

When you **only select an 8 Digit Watershed, it does not pre-populate the 6 Digit Watershed or filter the 12 Digit Watershed.

When you **only select a 12 Digit Watershed, it does not prepopulate the six and eight-digit watershed number and name.

**The filtering seems to work when you select certain counties and districts - only the watersheds available in those districts and counties display. This bug is only an issue when watershed is your only criteria.

**Comment by dhenry-KCI** [comment]
When the user selects a 6 digit watershed the 8 and 12 filter correctly.

But when the user selects an 8 or a 12 digit watershed the widget does not pre-populate the 6 or the 8.

**Comment by TaraF** [comment]
Dustin -- there seem to be some problems in the data to support this backwards filtering. For example, selecting by an 8 digit watershed in Baltimore County, district 4, will yield results:

http://vm-city102/TMDL/api/Domains/Get8DigitWatersheds?district=4&county=03&startsWith=&format=xml&shop= 

But if you were to do the same against the 6 digit, some seem to be missing (look for 021202 in both places):

http://vm-city102/TMDL/api/Domains/Get6DigitWatersheds?district=4&county=03&format=xml&shop=

Ehsan, could you verify that is a data issue (not service issue)?

Thanks!

**Comment by ehsan67** [comment]
@TaraF  I checked the data , there is no watershed 021202 in D_Watershed_6 domain

**Comment by rmeitl** [comment]
@dhenry-KCI , I think this is still an issue? When selecting a 6 digit, it doesn't refine results for 8 or 12.

**Comment by BrittanyHuber** [comment]
This has been fixed (also logged as issue #92 ). 6 digit is now being populated on 8 digit change, however, 12 digit can never be auto selected at this point, only filtered to the 8 digit chosen.
