### ISSUE TITLE
Reduction Tab (TMDL-Widget)- Missing Fields - 6.33B

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#50]
Please add the following services and fields to vertical Reduction tab:
Nutrient Concentrations <NUTRIENT_CON>
Bulk Density of Soil <BULK_DENSITY_SOIL>
Soil Erosion <SOIL_EROSION>
Calculation Method <CALC_METHOD> Decode domain D_CALC_Method

**Comment by ecomwu** [comment]
Ehsan, could you help me add domain service for D_CALC_Method? @ehsan67

**Comment by ehsan67** [comment]
@ecomwu  http://vm-city102/TMDL/Help/Api/GET-api-Domains-GetCalcMethods

**Comment by ecomwu** [comment]
I've added those fields and committed the changes. Please test it later

**Comment by dhenry-KCI** [comment]
Fixed
