### ISSUE TITLE
Zoom to Selected Feature - (TMDL-Widget) 6.12.3

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#52]
When the user zooms to a selected feature (this occurs on all trees plantings, outfall stabilizations and pavement removal for both assets and site selection) no feature is visible. - Is there scale dependency set?

**Comment by TaraF** [comment]
Per our last meeting, scale dependencies were agreed upon and set in the mxds and services were recreated.  This was not causing the selection / freeze which was determined to be a data issue for certain types.
