### ISSUE TITLE
Zoom to Selected Feature - (TMDL-Widget) Zoom Scale 6.12.3

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#53]
For all features except stream assets and stream site selection, the zoom scale set for each feature is to close. When the user zooms to a feature the user should be able to see a larger overview of the area. See attached example.
![zoomscale](https://cloud.githubusercontent.com/assets/4129185/3327797/6be46fe0-f7b4-11e3-9b98-2c992bb975db.JPG)

**Comment by ecomwu** [comment]
I've changed the code and committed changes. Please test it later. @dhenry-KCI

**Comment by BrittanyHuber** [comment]
Tested and is working...

![image](https://cloud.githubusercontent.com/assets/8092133/5455295/46edaeb8-8508-11e4-824d-2d5bf119118a.png)
