### ISSUE TITLE
Add Contracts (TMDL - Widget) - Refresh - 6.59

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#54]
A new contract that is added is not immediately visible unless the user clicks on the Consultant tab and then clicks back to the Contracts tab. The same thing occurs when the user deletes a contract.

**Comment by TaraF** [comment]
Refresh is now working properly on add, delete and edit of contracts.

**Comment by dhenry-KCI** [comment]
Looks good, fixed.
