### ISSUE TITLE
Admin Contracts - (TMDL-Widget)- Contract Fields -6.59.1

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#57]
The Contract type field in the grid should be a dropdown not text input.
 We are also missing the following VIEW ONLY fields in the Contract grid:
Ad Date <AD_DATE>
Bid Date <BID_DATE>
NTP Date <NTP_DATE>

**Comment by TaraF** [comment]
Updated. Please test once new version is out.

**Comment by dhenry-KCI** [comment]
Fixed
