### ISSUE TITLE
Add Contracts (TMDL - Widget) - Save Edits - 6.61

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#58]
When the user updates the contract grid and the clicks Save edits, a pop-up appears asking the user if they would like to save their edits. The user selects "yes" and the edits appear to Save. WHen the user selects a different contract and then goes back to the one they edited no edits are saved.

**Comment by TaraF** [comment]
Updated. Please review when new version is ready.

**Comment by dhenry-KCI** [comment]
Fixed
