### ISSUE TITLE
Admin Contracts- (TMDL-Widget) - View Associated Assets- 6.65

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#59]
For all contracts selected, the widget is only returning a single asset. The widget should see all assets for a particular contract.

To recreate- select contract Number : AT0875182-
the user should be able to filter through 12 Assets

**Comment by TaraF** [comment]
These items are scrollable in window.  I made the window larger, as it looked like it was being cut off.  Please test once new version is out.

**Comment by dhenry-KCI** [comment]
Fixed
