### ISSUE TITLE
Admin Contracts (TMDL-Widget)- Asset Grid- 6.66

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#61]
It appears that the values being pulled in to the Asset grid for each contract are in correct. For example , the TMDL_ID value being displayed = WIP, the Type = Proposed, and the Status Field = <Null>. See attached screen shot.
![admin -contract grid_1](https://cloud.githubusercontent.com/assets/4129185/3329970/fcb5c3c2-f7cb-11e3-87de-af138fbdee36.JPG)

**Comment by TaraF** [comment]
This has been fixed.  Please review with next updated release.

**Comment by dhenry-KCI** [comment]
Fixed
