### ISSUE TITLE
Admin Contracts (TMDL-Widget)  Create New Contract- 6.59

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#63]
The system should include text within the Create New Contract window that alerts the user that fields with an \* are required.

**Comment by TaraF** [comment]
There is now text, "*required fields" at the bottom, but also it is validated by requiring the user to enter a contract # and contract type before finishing the request.  Please review with next update.

**Comment by dhenry-KCI** [comment]
Can we lower the "*required field" text so that it is located in the lower left corner in the Create New Contract box (see red box in attached image)
![req_fields](https://cloud.githubusercontent.com/assets/4129185/3469728/c5408cb4-02b2-11e4-8579-f58f1c7df77a.JPG)

**Comment by TaraF** [comment]
This is fixed, please review with next release.

**Comment by dhenry-KCI** [comment]
Looks good.
