### ISSUE TITLE
Admin Contracts (TMDL-Widget)  Associate Consultant- 6.59

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#64]
If the user adds a consultant to a contract it correctly appears in the associated Cosultant firm grid under the Contracts tab. How does the user delete a consultant from a contract if it was mistakenly associated to a contract?

**Comment by TaraF** [comment]
Agreed, this is an issue, and wasn't established in the documentation.  Do you have a recommendation on a fix? Or can we sit down and discuss to come up with a resolution?

**Comment by TaraF** [comment]
This enhancement is added. Please review with next release.

**Comment by dhenry-KCI** [comment]
Fixed!
