### ISSUE TITLE
LUC Practice/ Other Tab- (TMDL-Widget)

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#66]
The fields for LUC Practice under the "Other Tab" should be moved to the General Tab for the following features:
Trees
Pavement Removal
Wetlands

The Other Tab should be removed.

**Comment by ecomwu** [comment]
I've changed it and committed already. Please test it later.

**Comment by dhenry-KCI** [comment]
Fixed
