### ISSUE TITLE
TMDL Form Selection (TMDL-WIDGET)- Selection has found no results.

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#67]
When the user filters and valid results are returned the widget will alert the user that the selection has returned no results.

To recreate:
Select by Site Selection- Tree Site Selection
District 4
Baltimore

![no results](https://cloud.githubusercontent.com/assets/4129185/3499080/0edfca1e-05fc-11e4-9ff1-af4c767d4c98.JPG)

**Comment by ecomwu** [comment]
Tara, could you take a look at this issue? I thought both strategy and site selection have similar issue relates to TMDLSelectionServices. @TaraF

**Comment by TaraF** [comment]
This is fixed. Please test with next release.
