### ISSUE TITLE
Stream Restoration (TMDL-WIDGET)- 6.27- General Information Fields

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#69]
Please change the "Name" field under the General tab for Stream Restoration to Stream Name. Please get the value for this field from STREAM_RESTORATION.Stream_Name

**Comment by ecomwu** [comment]
I've changed that field with Stream_Name. Please test it later

**Comment by dhenry-KCI** [comment]
Maggie- The "Name" field is pulling in the correct value, but please rename the field to "Stream Name"

**Comment by ecomwu** [comment]
I've fixed this and committed the code already. Please test it later.
