### ISSUE TITLE
VIEWING SELECTION RESULTS- (TMDL WIDGET)- Mechanical Street Sweeping- 6.30

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#7]
When the user filters by Strategy Type= Mechanical Street Sweeping the results are returing multiple assets with the same Stru_ID. Also for those records with mulitple STRU_ID's the following errorr appears:

**Comment by ehsan67** [comment]
fixed
