### ISSUE TITLE
Sweeping Route Lines (TMDL-Widget)- 6.30.3- Vewi associated Route lines

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#70]
When the user selects a related plan segment for a sweeping plan the application should zoom to the selected plan segment. 
*each Sweeping segment is related to a single route line.

**Comment by ehsan67** [comment]
@TaraF @ecomwu  @dhenry-KCI  I added a service for that:

http://vm-city102/TMDL/Help/Api/GET-api-Strategies-GetSweepingSegmentBoundingBox_sweepingSegmentId_version

**Comment by ecomwu** [comment]
I've added this feature to selected plan segment. But there is a data issue for some segment which doesn't have polygon information return.

**Comment by TaraF** [comment]
Dustin - not sure why I have been assigned here.  Passing it back to you--please let me know if there is something you would like me to do.

**Comment by dhenry-KCI** [comment]
Maggie- within the widget when the user clicks on a Sweeping Plan, the widget should zoom to the multiple segments that create the plan. Then when the user clicks on a specific plan segment the widget should zoom to the individual segment. Currently the widget is zooming to the individual segment first, and then when the user clicks on a a segment the feature disappears from the map and nothing is being displayed.

To recreate:
Strategies> Mechanical Street Sweeping> Anne Arundel County

TMDL ID - 020001US- this plan consists of 5 segments but only one segment is being displayed

**Comment by ecomwu** [comment]
I've fixed this issue and committed it already. Please test it later.
