### ISSUE TITLE
Street Sweeping Plan (TMDL Widget) - 6.30 - Sweeping Plan - General tab fields

### ISSUE THREAD

**Issue by rmeitl** [dhenry-KCI/TMDL-_Tracking-Widget#72]
Remove the following fields:
Fiscal Year
Total Miles Swept
Swept By
Date Entered
Actual Sweep
User Name
General Comments (The second one that is not showing data)

(These fields are related to the sweeping activity tab in requirement 6.30.6)

![untitled](https://cloud.githubusercontent.com/assets/7804977/3526176/dd8fd088-0779-11e4-998c-1954547d4e04.jpg)

**Comment by ecomwu** [comment]
I've fixed this issue. Please test it later.
