### ISSUE TITLE
TMDL reduction information (TMDL Widget) - 6.33B Field names

### ISSUE THREAD

**Issue by rmeitl** [dhenry-KCI/TMDL-_Tracking-Widget#73]
In the Reduction tab change the following field names:

the second Phosphorus (EOS) to Phosphorus (DEL)
the second Sediment (EOS) to Sediment (DEL)
Impr Equivalent Acres to Impv Equivalent Acres

![untitled2](https://cloud.githubusercontent.com/assets/7804977/3527051/55768c5c-0781-11e4-9f06-41d28eac97b3.jpg)

**Comment by ecomwu** [comment]
I've changed the field names. Please test it later.
