### ISSUE TITLE
Selection Form (TMDL Widget) 6.11.12 TMDL ID does not display when filtering by Contract

### ISSUE THREAD

**Issue by rmeitl** [dhenry-KCI/TMDL-_Tracking-Widget#74]
6.11.12
whenever a filter by contract is applied to any TMDL strategy, the TMDL ID does not return results.

![untitled3](https://cloud.githubusercontent.com/assets/7804977/3527392/959997fe-0784-11e4-8104-b8775b47da65.jpg)

**Comment by ehsan67** [comment]
fixed
