### ISSUE TITLE
Consultants (TMDL Widget) 6.34.3 - View Consultants

### ISSUE THREAD

**Issue by rmeitl** [dhenry-KCI/TMDL-_Tracking-Widget#75]
6.34.3
Doesn't allow user to view consultants associated with a contract.

the TMDL_CONTRACT table is related to CONSULTANT_CONTRACT junction table which is related to the CONSULTANT table.

![untitled4](https://cloud.githubusercontent.com/assets/7804977/3527567/5b0224a6-0786-11e4-9e27-79f72928d92e.jpg)

**Comment by ehsan67** [comment]
@rmeitl  can you provide me steps to recreate the problem?

**Comment by rmeitl** [comment]
-Filtered by swales in Baltimore county
-selected swale 030584
-viewed contracts tab
-changed to contract AX2645182 (which i know has a consultant associated to it)
-Then clicked on the tab that says View Consultants
-Error

But anytime you try to click on the view consultants tab it gives you this error regardless of whether or not a contract has consultants.

**Comment by ehsan67** [comment]
@ecomwu  I captured the request from the widget to get consultants and I see a typo in it: ( look at Cnsultants)

http://vm-city102/TMDL/api/Cnsultants/GetByContractNumber?browsernocache=Wed%20Jul%209%2013%3A30%3A27%20GMT%2D0400%202014&version=eGISW&contractNumber=HA2915124&format=xml

**Comment by ecomwu** [comment]
This is fixed. But we don't have "View Consultant" interface mockup, there is no where to display the data. Do we need to display the consultant details? If yes, do we have the mockup? @dhenry-KCI

**Comment by ecomwu** [comment]
I've completed the change which displaying the consultant(s) information under contract tab and removing the "View Consultant' button already. It's ready for testing with next release.

**Comment by dhenry-KCI** [comment]
Fixed
