### ISSUE TITLE
Tree Inspections (TMDL Widget) 6.36.1 Tree inspection field alias updates

### ISSUE THREAD

**Issue by rmeitl** [dhenry-KCI/TMDL-_Tracking-Widget#77]
6.36.1
Maybe we should abbreviate at breast height? Currently the word 'Height' is hidden since the name is so long, so our field ends in 'Breast' when you initially look at inspecitons. :punch:  :-1:  :zap:  :unamused: On another note, I just discovered some emoticons. :smile: 

Update Aliases to the following:
'Trees <2inch at Breast Height'      change to  'Trees <2in at BH'

'Trees >2inch at Breast Height'      change to  'Trees >2in at BH'

'Alias TBD'                           change to  'Percent >2in at BH'

Also, for Percent >2in at BH - it should pull data from field PER_GREATERTHAN_2IN_ATBH

**Comment by ecomwu** [comment]
I've changed those three field alias name. :smile:
