### ISSUE TITLE
Admin Tab (TMDL-Widget)- 6.60 - Editing under the Admin Tab

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#78]
The widget allows the user to edit fields in the contract table under the admin tab even though the "Enable editing" tab has not been checked. 

The edits don't save (i clicked on the selection tab and then clicked back to admin tab and the edits hadn't been saved), but the widget will keep the edits until the user switches tabs or contracts.

**Comment by TaraF** [comment]
This is fixed. Please review with next release.
