### ISSUE TITLE
SELECTION (TMDL WIDGET)- COUNTY FILTER

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#8]
When using SELECT BY FORM, the COUNTY dropdown filter is missing the following COUNTY values:
QUEEN ANNE"S
St. MARY"S
SOMERSET
TALBOT
WASHINGTON
WICOMICO
WORCESTER
BALTIMORE CITY

These values should be added to the dropdown.

**Comment by ehsan67** [comment]
I checked the database, we don't have theses counties in our database @dhenry-KCI

**Comment by dhenry-KCI** [comment]
Brendan,
The domain table dropped these values. This is just a reminder to re-add these values to the domain table
