### ISSUE TITLE
Impervious Surface Elimination Error (TMDL Widget) - general bug

### ISSUE THREAD

**Issue by rmeitl** [dhenry-KCI/TMDL-_Tracking-Widget#80]
If I filter by Cecil County or District 2, I get results for Impervious Surface Elimination Strategy. If I filter by anything else, I get the error below.

To recreate the error below, select Impervious Surface Elimination and filter by Frederick County or District 7. This same error happens if you select All TMDL Strategies and filter by counties other than Cecil.

![untitled10](https://cloud.githubusercontent.com/assets/7804977/3552953/2273af00-08fe-11e4-8140-3bd8d8adf97c.jpg)

**Comment by ehsan67** [comment]
fixed
