### ISSUE TITLE
Export Functionality (TMDL-Widget) 6.12.12- Check box functionality

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#81]
The pop-up that is associated with the export button includes a checkbox to alert the user which features they would like exported when multiple features are selected. If only one feature is selected though the widget doesn't alert the user to check the box or not.

Do one of the following to fix:
1. Remove the checkbox when a single feature type is selected
2. Have the checkbox already checked (and unselectedable) when a single feature type is selected
3. Alert the user that they must check the feature box to export a feature.

**Comment by TaraF** [comment]
This has been fixed, via #3 above. Please review with next release.
