### ISSUE TITLE
TMDL Results- Sandfilters

### ISSUE THREAD

**Issue by dhenry-KCI** [dhenry-KCI/TMDL-_Tracking-Widget#84]
Maggie- I am receiving an error when i try to view sand filters within the widget.
I have attached a screen shot of the error.

To recreate:
TMDL STRATEGIES > Sand filter

12 Digit Watershed = 021311040940

![sand filters](https://cloud.githubusercontent.com/assets/4129185/3802340/160c7440-1c0e-11e4-98d2-79a0562eb208.PNG)

**Comment by ecomwu** [comment]
The issue is fixed. But still no data return. I'm not sure whether it's data issue or not. 
@ehsan67 , could you help me to take a look at it?

**Comment by ehsan67** [comment]
@ecomwu It is fixed
