### ISSUE TITLE
Select by Map - 6.11 - select by map returns no results

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#85]
When the user attempts to select by map, no results are returned.

![polygon](https://cloud.githubusercontent.com/assets/8092133/4738882/39b741a6-5a00-11e4-8052-2d58d2ea058c.JPG)

![capture](https://cloud.githubusercontent.com/assets/8092133/4738663/b3b4a9f0-59fe-11e4-848a-577752504bf7.JPG)

Steps to recreate:
Selection Tab > Map
Select By TMDL Strategies > Planting Trees or forestation on Pervious Urban
Drew a polygon in Baltimore County > double clicked to finish > widget pops up with a dialog box stating no results

**Comment by TaraF** [comment]
http://shagbdapp/TMDL/api/Strategies/GetByPolygon?version=eGISW&strategyType=FPU

not returning any results.

**Comment by TaraF** [comment]
Please test on http://shagbdapp/egis/viewer.html

**Comment by BrittanyHuber** [comment]
Tara, 

While testing this, the error dialog does not show up anymore, however it is not returning any results. 

To recreate:
make a selection by form then when attempting to select by map, after drawing polygon it sends you back to the select by map form, and does not return any results. 

Selection Tab > Form
Select By TMDL Strategies > Swales
Filter by Geography > District 4 > County Baltimore (46 features return)
Then Filter by Watershed > 6 Digit > Gunpowder River (27 Records return)

Selection Tab > Map
Select By TMDL Strategies > Planting Trees
Begin selection > drew polygon around Harford County
Sends back to selection tab instead of results tab, and no results are returned. 

When refreshing the webpage and selection by map before selecting by form, results are returned.

**Comment by BrittanyHuber** [comment]
![image](https://cloud.githubusercontent.com/assets/8092133/5473275/1332eac4-85d6-11e4-8b66-372b8107d47e.png)

**Comment by BrittanyHuber** [comment]
![image](https://cloud.githubusercontent.com/assets/8092133/5473354/ca715c48-85d6-11e4-8eb0-d07e9188c0bc.png)

**Comment by TaraF** [comment]
Dustin,
I cannot replicate this error.  I have run through the steps to recreate with Brittany, and did a screen share while remoting into my SHA box.  Following her steps, we were able to get the appropriate selection, without any issues like she is reporting above.  

When testing again, Brittany was able to replicate the issue on her machine.  I am not sure what the difference would be, but the only thing I can suspect is that the server return she receives is slow, and does not make it to calling the appropriate service in a timely manner.  

I asked Brittany to run it from IE (she was using Chrome), but to the same effect.  Do you think it would be effective to have her test again from another machine that she doesn't typically work from, or let someone else down at SHA test to see if they experience the same error from their machine?

I don't believe it is a widget or services error, as I am able to run it ok, therefore I am not sure there is much for me to do to fix this.

Thanks,
Tara

**Comment by BrittanyHuber** [comment]
@TaraF , 

I believe resetting the values in the select by map tab so that none of the fields remain populated from the previous selection should take care of this issue. 

Brittany

**Comment by BrittanyHuber** [comment]
@TaraF this could be directly related to the map service.

Select by map > site selections > all tmdl site selections > polygon (anywhere)  > returns no results. 

strategies seem to be working

**Comment by TaraF** [comment]
This was a combination issue -- issue in flex code(fixed) and issue with oracle packages (fixed by Ehsan).  This item is fixed, please wait to test for next push to KCI dev.

**Comment by BrittanyHuber** [comment]
tested on SHA and is working
