### ISSUE TITLE
Select by Map - 6.11 - select by map not identifying results

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#86]
When the user selects by map, a dialog box pops up stating that no results were returned. When clicking on results tab, it states that a number of results were returned, with no actual results results returned. 

![results_tab](https://cloud.githubusercontent.com/assets/8092133/4739117/20f8ad10-5a02-11e4-90f2-42a1814e7f11.JPG)

Steps to recreate: 
Selection Tab > Map
Select By TMDL Strategies > Planting Trees or forestation on Pervious Urban
Drew a polygon around Harford County > no results dialog box returned
Clicked on Results tab > 129 results returned stated, with no actual results returned

**Comment by TaraF** [comment]
This is fixed. Please wait to test until it is in SHA test.

**Comment by TaraF** [comment]
Please test on http://shagbdapp/egis/viewer.html

**Comment by BrittanyHuber** [comment]
Tested and it is working.
