### ISSUE TITLE
Select by Form (TMDL-Widget) 6.11 - unable to select by form after selecting by map

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#88]
When attempting to select by map failed, going back to select by form and trying to select by county, the option to click select is grayed out.

![selectfail](https://cloud.githubusercontent.com/assets/8092133/4739451/c65d1474-5a04-11e4-9b4a-4574f5b91c4f.JPG)

Steps to Recreate:
Selection Tab > Map
Select By TMDL Strategies > Planting Trees or forestation on Pervious Urban
Drew a polygon around Harford County > no results 
Selection Tab > Form
Click Reset
Select By TMDL Strategies > Planting Trees or forestation on Pervious Urban
Filter by Geography > District 4 > County Harford > Shop Churchville
Unable to press Select

Closing out of the internet and reopening enables select by form to work.
Changing strategies allows user to select by form again (seems to only be tree planting).

**Comment by TaraF** [comment]
Hi Brittany,

I am unable to replicate after following the steps above.  Could you let me know if this still persists for you? 

Thanks,
Tara

**Comment by BrittanyHuber** [comment]
Tara, 

I encountered this issue again. 

![image](https://cloud.githubusercontent.com/assets/8092133/5360172/a401f35c-7f90-11e4-90e6-a6a2abee5fb8.png)

Steps to recreate:
Selection Form
Select by TMDL Strategies > Swales
Filter by: Geography > Distrct 5
Validate and Select
Switch Selection > map
Select by TMDL strategies > swales
large polygon drawn
sites returned
Selection > form
Filters (Geography and District 5) remain populated from previous select by Form, Select by (TMDL Strategies and Swales) has been cleared
Select by TMDL Strategies > Swales
Filter By Geography > District 5
Validate and Select buttons not able to select

when trying to refresh my browser after this problem I receive the following errors: 

![image](https://cloud.githubusercontent.com/assets/8092133/5360247/095e727a-7f91-11e4-94bc-5fc9f7bd3afa.png)

![image](https://cloud.githubusercontent.com/assets/8092133/5360254/134a808a-7f91-11e4-8aaf-c1c533e5bc37.png)

Let me know if this is confusing!

Brittany

**Comment by TaraF** [comment]
This issue is fixed. Please wait to test until pushed to shagbdapp.

**Comment by BrittanyHuber** [comment]
fixed.

**Comment by BrittanyHuber** [comment]
Tested on SHA network and is fixed.
