### ISSUE TITLE
Select by Form (TMDL-Widget) 6.11 - results window fails to update when new selection returns no results

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#89]
When selecting by form, the results window does not update the number of features returned when a new selection is made and nothing is returned. It will update when the new selection returns data.

![balt46](https://cloud.githubusercontent.com/assets/8092133/4740328/26376b18-5a0c-11e4-9e46-83963af6e524.JPG)

![gunpowder27](https://cloud.githubusercontent.com/assets/8092133/4740333/2b3b1ac4-5a0c-11e4-93fa-6845c2e3a5f5.JPG)

![says27](https://cloud.githubusercontent.com/assets/8092133/4740335/2d5c1830-5a0c-11e4-8340-275b31e30f5b.JPG)

Steps to Recreate: 
Selection Tab > Form
Select By TMDL Strategies > Swales
Filter by Geography > District 4 > County Baltimore (46 features return)
Then Filter by Watershed > 6 Digit > Gunpowder River (27 Records return)
Then Filer by 8 Digit > Pretty boy Reservoir (No features return but the results say 27 results)

**Comment by TaraF** [comment]
This has been fixed. Please wait to test until in SHA test.

**Comment by TaraF** [comment]
Please test on http://shagbdapp/egis/viewer.html

**Comment by BrittanyHuber** [comment]
Tested and it works.
