### ISSUE TITLE
Select by Form (TMDL-Widget) 6.11 - wetland site selection appears twice

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#90]
Wetland site selection is listed twice in the drop down menu when selecting by site selection.

![wetland](https://cloud.githubusercontent.com/assets/8092133/4740687/79260836-5a0f-11e4-9e59-c9c87e4c4270.JPG)

Steps to recreate: 
Selection Tab > Form
Select By Site Selection > Wetland Site Selection (appears twice)

**Comment by TaraF** [comment]
Brendan,
Can you take a look at this one with me? 

This is on the data / domain side.  The code and description are duplicating itself for Wetland:  http://shagbdapp/TMDL//api/Domains/GetSiteSelectionNames?format=xml&browsernocache=Wed%20Oct%2029%2009%3A01%3A54%20GMT%2D0400%202014

**Comment by BrittanyHuber** [comment]
Does not appear twice anymore.

![image](https://cloud.githubusercontent.com/assets/8092133/5455396/2b49175a-8509-11e4-9436-b6cabc5379d0.png)
