### ISSUE TITLE
Select by Form (TMDL-Widget) 6.11.10 - shop does not prepopulate district and county

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#91]
When selecting by form, within the filtered options the system does not allow you to select a shop in order to prepopulate district and county values. 

![shop](https://cloud.githubusercontent.com/assets/8092133/4742619/8161c97a-5a20-11e4-83e3-7f0ab5868bf3.JPG)

Steps to recreate:
TMDL Strategies > Planting Trees
Filter by geography > shops (drop down menu does not provide a list of shops to choose from)

**Comment by TaraF** [comment]
This was previously discussed -- and was decided that we would not support backwards filtering from the Shop value.  User must select a County before being able to select a Shop.   

I can probably dig up the documentation on this issue if necessary.
