### ISSUE TITLE
Select by Form (TMDL-Widget) 6.11.10 - 8-digit watershed does not prepopulate 6 and 12-digits

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#92]
When selecting by form, within the filtered options the system does not prepopulate the 6-digit watershed and 12-digit watershed when the 8-digit watershed is selected. 

![8digit](https://cloud.githubusercontent.com/assets/8092133/4742699/1f441ad0-5a21-11e4-993c-e30733c79068.JPG)

Steps to recreate:
TMDL Strategies > Planting Trees
Filter by geography > watershed
8 digit watershed > Big Elk Creek (populates associated 8-digit number only)

**Comment by TaraF** [comment]
This has been fixed. Please wait to test until in SHA test. Also, please note, 6 digit is now being populated on 8 digit change, however, 12 digit can never be auto selected at this point, only filtered to the 8 digit chosen.

**Comment by TaraF** [comment]
Please test on http://shagbdapp/egis/viewer.html.  (please also see note above)

**Comment by BrittanyHuber** [comment]
Tested and its working.
