### ISSUE TITLE
Select by Form (TMDL-Widget) 6.11.10 - 12-digit watershed does not prepopulate 6 digit name/number

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#93]
When selecting by form, within the filtered options the system does not prepopulate the 6-digit name and or number when 12-digit watershed is selected. 

![12dig](https://cloud.githubusercontent.com/assets/8092133/4742814/0cfbef32-5a22-11e4-8d1d-e72b0466862d.JPG)

![12dig2](https://cloud.githubusercontent.com/assets/8092133/4742872/9b6e34aa-5a22-11e4-9e68-648d5e295f33.JPG)

Steps to recreate:
TMDL Strategies > Planting Trees
Filter by geography > watershed
12 digit watershed > 021301060674 (populates all but 6 digit number)

TMDL Strategies > Planting Trees
Filter by geography > watershed
12 digit watershed > 02120202030344 (does not populate 6 digit name or number)

**Comment by TaraF** [comment]
This has been fixed.  Please wait to test until in SHA test.  Also, please note, that there has to be data to support all levels of watershed.  For example, 021202 does NOT exist in db, therefore will never be populated.

**Comment by TaraF** [comment]
Please test on http://shagbdapp/egis/viewer.html

**Comment by BrittanyHuber** [comment]
Tested and its working.
