### ISSUE TITLE
Feature Manager (TMDL-Widget) - 6.12.3 - asset editor web service error

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#94]
When selecting by form, the Asset Editor encounters a web service error when selecting by certain assets and site selection features. In some cases the general information results are returned, while in others no results are returned. 

![error](https://cloud.githubusercontent.com/assets/8092133/4743346/d0f41564-5a26-11e4-98ef-d15a85136f5f.JPG)

![catach](https://cloud.githubusercontent.com/assets/8092133/4743347/d2d758b4-5a26-11e4-8fd6-e5a14e697dbc.JPG)

TMDL Strategies > Planting Trees 
Filter by geography > District 5 > Anne Arundel
113 results
Select any individual asset > Error
Select ok > general information is returned

TMDL Strategies > Catch Basin Cleaning 
Filter by geography > District 5 > Anne Arundel
10 results
Select any individual asset > Error
Select ok > general information is NOT returned

**Comment by TaraF** [comment]
For the first case above, the error message displayed is associated with this service issue (previously noted in another bug): http://shagbdapp/TMDL/api/Strategies/GetLucPractices? 

For the second case, the error message displayed is associated with this service:  http://shagbdapp/TMDL/api/Strategies/GetLRInletCleaningGeneralInfo?browsernocache=Wed%20Oct%2029%2010%3A32%3A54%20GMT%2D0400%202014&version=eGISW&activityId=ED000FBB32BE40A5B7DE59B643463ABB&format=xml   and is why there is no info shown in the general tab.  Information does however show up in other tabs.

http://shagbdapp/TMDL/api/Strategies/GetLRInletCleaningGeneralInfo?activityId=59DB2D758E99436B84A9DBEA937151EB&version=eGISW&format=xml

**Comment by TaraF** [comment]
This is fixed, please wait to test.

**Comment by TaraF** [comment]
Please test on http://shagbdapp/egis/viewer.html

**Comment by BrittanyHuber** [comment]
Tested both and they are working.
