### ISSUE TITLE
Feature Manager (TMDL-Widget) - 6.21 - not able to access associated documents

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#96]
The system does not allow the user to display associated documents for any records. 

![documents](https://cloud.githubusercontent.com/assets/8092133/4743692/134663d8-5a2a-11e4-9c89-8950611b9034.JPG)

![notavail](https://cloud.githubusercontent.com/assets/8092133/4743695/178f9a68-5a2a-11e4-8128-06b5afd5c69c.JPG)

Steps to recreate:
select by form > TMDL Strategies > Planting Trees or Forestation on Pervious Urban
Filter by geography > District 2 > Cecil
070038UT has 2 associated documents that are not able to be accessed

**Comment by TaraF** [comment]
This is pointing to the wrong server:  vm-city102 instead of shagbdapp (http://vm-city102/TMDL/doc/AX7225168-FA-20101029.pdf)

--check config file and repoint
--or check code to make sure pointing to config file

**Comment by TaraF** [comment]
Hi Maggie,

Can you update any places you had this hardcoded (http://vm-city102/TMDL/doc/) in the TMDL code?  I did create a document URL to pull from the config file, so you can reference that (in TMDLComponent.as):

//document down URL
documentURL = configXML.webservices.downloadservice;//TF updated
//documentURL = "http://vm-city102/TMDL/doc/";

Also, it is probably a good time to check photos too, to make sure that is not hardcoded anywhere as well.  I also create a photoURL variable:

photoURL = configXML.webservices.photoservice; //TF updated
//photoURL = "http://vm-city102/TMDL/img/SS/";

When you are done, please reassign to me so I can push code and update the config to point to SHA document (and photo) locations. 

Thanks,
Tara

**Comment by ecomwu** [comment]
Hi Tara,

I've changed document and photo related URL issues. And I've already committed all changes I have so far, please feel free to check it and let me know if you have any issues.

Thanks,
Maggie

**Comment by ecomwu** [comment]
This issue has been fixed.

**Comment by TaraF** [comment]
Same issue as #106:

The issue here was that documentURL variable had been changed to a static value, instead of pulling from the config xml file like it had been previously:

Is: 
//documentURL = configXML.webservices.downloadservice;//TF updated
documentURL = "http://localhost/DocumentManagement/";

should be:
documentURL = configXML.webservices.downloadservice;//TF updated
//documentURL = "http://localhost/DocumentManagement/";

I will need to build a new release of the flex code to correct this problem. Please wait to test.

**Comment by TaraF** [comment]
Ready to test.

**Comment by BrittanyHuber** [comment]
Tested on SHA network, now able to access documents
