### ISSUE TITLE
Street Sweeping (TMDL-Widget) 6.30.4 - geometry missing

### ISSUE THREAD

**Issue by BrittanyHuber** [dhenry-KCI/TMDL-_Tracking-Widget#98]
The system returned an error that no geometry data was found for a street sweeping segment that exists in the database. 

![sweeper](https://cloud.githubusercontent.com/assets/8092133/4744000/896b6566-5a2c-11e4-8c81-93215aabd0ed.JPG)

Select by form > TMDL Strategies > Mechanical Street Sweeping
Filter by geometry > District 4 > 030001US

**Comment by TaraF** [comment]
This appears to be data issue.  There is no TMDL_ACTIVITY_ID = 'E4C50FC6C5214C478F2C590891047341'   in the map service query.   Either something is missing in the db to make the connection, or the map service may not have all the joins necessary to return (unlikely since the others are working ok)

**Comment by dhenry-KCI** [comment]
This feature is missing the route line geometry which is causing the error above.I will leave this open until the route line is added to the database.

**Comment by BrittanyHuber** [comment]
@dhenry-KCI added segments/geometry to the DEV and production environments and it fixed.
